// Code generated by ent, DO NOT EDIT.

package pending

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/improvtrace/stateflux/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldType, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldPriority, v))
}

// ExecMode applies equality check predicate on the "exec_mode" field. It's identical to ExecModeEQ.
func ExecMode(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldExecMode, v))
}

// RunAt applies equality check predicate on the "run_at" field. It's identical to RunAtEQ.
func RunAt(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldRunAt, v))
}

// TimeoutMs applies equality check predicate on the "timeout_ms" field. It's identical to TimeoutMsEQ.
func TimeoutMs(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldTimeoutMs, v))
}

// MaxAttempts applies equality check predicate on the "max_attempts" field. It's identical to MaxAttemptsEQ.
func MaxAttempts(v int32) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldMaxAttempts, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldAttempts, v))
}

// OwnerNode applies equality check predicate on the "owner_node" field. It's identical to OwnerNodeEQ.
func OwnerNode(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldOwnerNode, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldError, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldIdempotencyKey, v))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldBatchID, v))
}

// ParentTaskID applies equality check predicate on the "parent_task_id" field. It's identical to ParentTaskIDEQ.
func ParentTaskID(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldParentTaskID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldUpdatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContainsFold(FieldType, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContainsFold(FieldPriority, v))
}

// ExecModeEQ applies the EQ predicate on the "exec_mode" field.
func ExecModeEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldExecMode, v))
}

// ExecModeNEQ applies the NEQ predicate on the "exec_mode" field.
func ExecModeNEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldExecMode, v))
}

// ExecModeIn applies the In predicate on the "exec_mode" field.
func ExecModeIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldExecMode, vs...))
}

// ExecModeNotIn applies the NotIn predicate on the "exec_mode" field.
func ExecModeNotIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldExecMode, vs...))
}

// ExecModeGT applies the GT predicate on the "exec_mode" field.
func ExecModeGT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldExecMode, v))
}

// ExecModeGTE applies the GTE predicate on the "exec_mode" field.
func ExecModeGTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldExecMode, v))
}

// ExecModeLT applies the LT predicate on the "exec_mode" field.
func ExecModeLT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldExecMode, v))
}

// ExecModeLTE applies the LTE predicate on the "exec_mode" field.
func ExecModeLTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldExecMode, v))
}

// ExecModeContains applies the Contains predicate on the "exec_mode" field.
func ExecModeContains(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContains(FieldExecMode, v))
}

// ExecModeHasPrefix applies the HasPrefix predicate on the "exec_mode" field.
func ExecModeHasPrefix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasPrefix(FieldExecMode, v))
}

// ExecModeHasSuffix applies the HasSuffix predicate on the "exec_mode" field.
func ExecModeHasSuffix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasSuffix(FieldExecMode, v))
}

// ExecModeEqualFold applies the EqualFold predicate on the "exec_mode" field.
func ExecModeEqualFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEqualFold(FieldExecMode, v))
}

// ExecModeContainsFold applies the ContainsFold predicate on the "exec_mode" field.
func ExecModeContainsFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContainsFold(FieldExecMode, v))
}

// RunAtEQ applies the EQ predicate on the "run_at" field.
func RunAtEQ(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldRunAt, v))
}

// RunAtNEQ applies the NEQ predicate on the "run_at" field.
func RunAtNEQ(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldRunAt, v))
}

// RunAtIn applies the In predicate on the "run_at" field.
func RunAtIn(vs ...time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldRunAt, vs...))
}

// RunAtNotIn applies the NotIn predicate on the "run_at" field.
func RunAtNotIn(vs ...time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldRunAt, vs...))
}

// RunAtGT applies the GT predicate on the "run_at" field.
func RunAtGT(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldRunAt, v))
}

// RunAtGTE applies the GTE predicate on the "run_at" field.
func RunAtGTE(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldRunAt, v))
}

// RunAtLT applies the LT predicate on the "run_at" field.
func RunAtLT(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldRunAt, v))
}

// RunAtLTE applies the LTE predicate on the "run_at" field.
func RunAtLTE(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldRunAt, v))
}

// TimeoutMsEQ applies the EQ predicate on the "timeout_ms" field.
func TimeoutMsEQ(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldTimeoutMs, v))
}

// TimeoutMsNEQ applies the NEQ predicate on the "timeout_ms" field.
func TimeoutMsNEQ(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldTimeoutMs, v))
}

// TimeoutMsIn applies the In predicate on the "timeout_ms" field.
func TimeoutMsIn(vs ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldTimeoutMs, vs...))
}

// TimeoutMsNotIn applies the NotIn predicate on the "timeout_ms" field.
func TimeoutMsNotIn(vs ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldTimeoutMs, vs...))
}

// TimeoutMsGT applies the GT predicate on the "timeout_ms" field.
func TimeoutMsGT(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldTimeoutMs, v))
}

// TimeoutMsGTE applies the GTE predicate on the "timeout_ms" field.
func TimeoutMsGTE(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldTimeoutMs, v))
}

// TimeoutMsLT applies the LT predicate on the "timeout_ms" field.
func TimeoutMsLT(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldTimeoutMs, v))
}

// TimeoutMsLTE applies the LTE predicate on the "timeout_ms" field.
func TimeoutMsLTE(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldTimeoutMs, v))
}

// MaxAttemptsEQ applies the EQ predicate on the "max_attempts" field.
func MaxAttemptsEQ(v int32) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldMaxAttempts, v))
}

// MaxAttemptsNEQ applies the NEQ predicate on the "max_attempts" field.
func MaxAttemptsNEQ(v int32) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldMaxAttempts, v))
}

// MaxAttemptsIn applies the In predicate on the "max_attempts" field.
func MaxAttemptsIn(vs ...int32) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsNotIn applies the NotIn predicate on the "max_attempts" field.
func MaxAttemptsNotIn(vs ...int32) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsGT applies the GT predicate on the "max_attempts" field.
func MaxAttemptsGT(v int32) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldMaxAttempts, v))
}

// MaxAttemptsGTE applies the GTE predicate on the "max_attempts" field.
func MaxAttemptsGTE(v int32) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldMaxAttempts, v))
}

// MaxAttemptsLT applies the LT predicate on the "max_attempts" field.
func MaxAttemptsLT(v int32) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldMaxAttempts, v))
}

// MaxAttemptsLTE applies the LTE predicate on the "max_attempts" field.
func MaxAttemptsLTE(v int32) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldMaxAttempts, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldAttempts, v))
}

// OwnerNodeEQ applies the EQ predicate on the "owner_node" field.
func OwnerNodeEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldOwnerNode, v))
}

// OwnerNodeNEQ applies the NEQ predicate on the "owner_node" field.
func OwnerNodeNEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldOwnerNode, v))
}

// OwnerNodeIn applies the In predicate on the "owner_node" field.
func OwnerNodeIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldOwnerNode, vs...))
}

// OwnerNodeNotIn applies the NotIn predicate on the "owner_node" field.
func OwnerNodeNotIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldOwnerNode, vs...))
}

// OwnerNodeGT applies the GT predicate on the "owner_node" field.
func OwnerNodeGT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldOwnerNode, v))
}

// OwnerNodeGTE applies the GTE predicate on the "owner_node" field.
func OwnerNodeGTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldOwnerNode, v))
}

// OwnerNodeLT applies the LT predicate on the "owner_node" field.
func OwnerNodeLT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldOwnerNode, v))
}

// OwnerNodeLTE applies the LTE predicate on the "owner_node" field.
func OwnerNodeLTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldOwnerNode, v))
}

// OwnerNodeContains applies the Contains predicate on the "owner_node" field.
func OwnerNodeContains(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContains(FieldOwnerNode, v))
}

// OwnerNodeHasPrefix applies the HasPrefix predicate on the "owner_node" field.
func OwnerNodeHasPrefix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasPrefix(FieldOwnerNode, v))
}

// OwnerNodeHasSuffix applies the HasSuffix predicate on the "owner_node" field.
func OwnerNodeHasSuffix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasSuffix(FieldOwnerNode, v))
}

// OwnerNodeEqualFold applies the EqualFold predicate on the "owner_node" field.
func OwnerNodeEqualFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEqualFold(FieldOwnerNode, v))
}

// OwnerNodeContainsFold applies the ContainsFold predicate on the "owner_node" field.
func OwnerNodeContainsFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContainsFold(FieldOwnerNode, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContainsFold(FieldError, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v string) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...string) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldBatchID, vs...))
}

// BatchIDGT applies the GT predicate on the "batch_id" field.
func BatchIDGT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldBatchID, v))
}

// BatchIDGTE applies the GTE predicate on the "batch_id" field.
func BatchIDGTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldBatchID, v))
}

// BatchIDLT applies the LT predicate on the "batch_id" field.
func BatchIDLT(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldBatchID, v))
}

// BatchIDLTE applies the LTE predicate on the "batch_id" field.
func BatchIDLTE(v string) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldBatchID, v))
}

// BatchIDContains applies the Contains predicate on the "batch_id" field.
func BatchIDContains(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContains(FieldBatchID, v))
}

// BatchIDHasPrefix applies the HasPrefix predicate on the "batch_id" field.
func BatchIDHasPrefix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasPrefix(FieldBatchID, v))
}

// BatchIDHasSuffix applies the HasSuffix predicate on the "batch_id" field.
func BatchIDHasSuffix(v string) predicate.Pending {
	return predicate.Pending(sql.FieldHasSuffix(FieldBatchID, v))
}

// BatchIDEqualFold applies the EqualFold predicate on the "batch_id" field.
func BatchIDEqualFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldEqualFold(FieldBatchID, v))
}

// BatchIDContainsFold applies the ContainsFold predicate on the "batch_id" field.
func BatchIDContainsFold(v string) predicate.Pending {
	return predicate.Pending(sql.FieldContainsFold(FieldBatchID, v))
}

// CallbackIsNil applies the IsNil predicate on the "callback" field.
func CallbackIsNil() predicate.Pending {
	return predicate.Pending(sql.FieldIsNull(FieldCallback))
}

// CallbackNotNil applies the NotNil predicate on the "callback" field.
func CallbackNotNil() predicate.Pending {
	return predicate.Pending(sql.FieldNotNull(FieldCallback))
}

// ParentTaskIDEQ applies the EQ predicate on the "parent_task_id" field.
func ParentTaskIDEQ(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldParentTaskID, v))
}

// ParentTaskIDNEQ applies the NEQ predicate on the "parent_task_id" field.
func ParentTaskIDNEQ(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldParentTaskID, v))
}

// ParentTaskIDIn applies the In predicate on the "parent_task_id" field.
func ParentTaskIDIn(vs ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldParentTaskID, vs...))
}

// ParentTaskIDNotIn applies the NotIn predicate on the "parent_task_id" field.
func ParentTaskIDNotIn(vs ...int64) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldParentTaskID, vs...))
}

// ParentTaskIDGT applies the GT predicate on the "parent_task_id" field.
func ParentTaskIDGT(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldParentTaskID, v))
}

// ParentTaskIDGTE applies the GTE predicate on the "parent_task_id" field.
func ParentTaskIDGTE(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldParentTaskID, v))
}

// ParentTaskIDLT applies the LT predicate on the "parent_task_id" field.
func ParentTaskIDLT(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldParentTaskID, v))
}

// ParentTaskIDLTE applies the LTE predicate on the "parent_task_id" field.
func ParentTaskIDLTE(v int64) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldParentTaskID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Pending {
	return predicate.Pending(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pending) predicate.Pending {
	return predicate.Pending(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pending) predicate.Pending {
	return predicate.Pending(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pending) predicate.Pending {
	return predicate.Pending(sql.NotPredicates(p))
}
