// Code generated by ent, DO NOT EDIT.

package schedulable

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the schedulable type in the database.
	Label = "schedulable"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldExecMode holds the string denoting the exec_mode field in the database.
	FieldExecMode = "exec_mode"
	// FieldRunAt holds the string denoting the run_at field in the database.
	FieldRunAt = "run_at"
	// FieldTimeoutMs holds the string denoting the timeout_ms field in the database.
	FieldTimeoutMs = "timeout_ms"
	// FieldMaxAttempts holds the string denoting the max_attempts field in the database.
	FieldMaxAttempts = "max_attempts"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldOwnerNode holds the string denoting the owner_node field in the database.
	FieldOwnerNode = "owner_node"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldCallback holds the string denoting the callback field in the database.
	FieldCallback = "callback"
	// FieldParentTaskID holds the string denoting the parent_task_id field in the database.
	FieldParentTaskID = "parent_task_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the schedulable in the database.
	Table = "schedulable_tasks"
)

// Columns holds all SQL columns for schedulable fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldPriority,
	FieldExecMode,
	FieldRunAt,
	FieldTimeoutMs,
	FieldMaxAttempts,
	FieldAttempts,
	FieldOwnerNode,
	FieldError,
	FieldIdempotencyKey,
	FieldBatchID,
	FieldCallback,
	FieldParentTaskID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority string
	// DefaultExecMode holds the default value on creation for the "exec_mode" field.
	DefaultExecMode string
	// DefaultTimeoutMs holds the default value on creation for the "timeout_ms" field.
	DefaultTimeoutMs int64
	// DefaultMaxAttempts holds the default value on creation for the "max_attempts" field.
	DefaultMaxAttempts int32
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int64
	// DefaultOwnerNode holds the default value on creation for the "owner_node" field.
	DefaultOwnerNode string
	// DefaultError holds the default value on creation for the "error" field.
	DefaultError string
	// DefaultIdempotencyKey holds the default value on creation for the "idempotency_key" field.
	DefaultIdempotencyKey string
	// DefaultBatchID holds the default value on creation for the "batch_id" field.
	DefaultBatchID string
	// DefaultParentTaskID holds the default value on creation for the "parent_task_id" field.
	DefaultParentTaskID int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Schedulable queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByExecMode orders the results by the exec_mode field.
func ByExecMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecMode, opts...).ToFunc()
}

// ByRunAt orders the results by the run_at field.
func ByRunAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunAt, opts...).ToFunc()
}

// ByTimeoutMs orders the results by the timeout_ms field.
func ByTimeoutMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutMs, opts...).ToFunc()
}

// ByMaxAttempts orders the results by the max_attempts field.
func ByMaxAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAttempts, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByOwnerNode orders the results by the owner_node field.
func ByOwnerNode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerNode, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByParentTaskID orders the results by the parent_task_id field.
func ByParentTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentTaskID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
