// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"
	"github.com/google/wire"
	"github.com/improvtrace/stateflux/internal/config"
)

// Injectors from wire.go:

// InitializeApplication 是 wire 生成的装配入口（§15.1#1）：cmd/stateflux 只调用它。
func InitializeApplication(ctx context.Context, cfg config.Config) (*App, func(), error) {
	data, cleanup, err := dataOpen(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	dialer := provideDialer()
	eventBus, err := provideEventBus(cfg, data, dialer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registry, err := provideTaskRegistry()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	codec := provideCodec(registry)
	handlerRegistry, err := provideHandlerRegistry()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	view, err := provideClusterView(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache, cleanup2 := provideClusterCache(ctx, cfg, view)
	cacheviewView, err := provideCacheView(cfg, data)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	resultPublisher := provideResultPublisher(cfg, eventBus, cache, cacheviewView)
	metrics, err := provideMetrics()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtime := provideWorkerRuntime(cfg, eventBus, codec, handlerRegistry, resultPublisher, cacheviewView, metrics)
	snowflake := provideSnowflake(cfg)
	store := provideStore(data, snowflake)
	collector := provideCollector(store, metrics)
	executorServer := provideExecutorServer(runtime, collector, metrics)
	workerRegistry, err := provideCapabilityRegistry()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	capabilityServer := provideCapabilityServer(workerRegistry, metrics)
	dispatcher := provideDispatcher(cfg, eventBus, cache, cacheviewView, codec, metrics)
	forwarder := provideForwarder(cfg, dialer, cache)
	dispatchServer := provideDispatchServer(cfg, dispatcher, cache, forwarder, metrics)
	coherenceStore := provideCoherenceStore()
	coherenceServer := provideCoherenceServer(coherenceStore, cacheviewView, metrics)
	forwardRegistry := provideForwardRegistry()
	server := provideForwardServer(cfg, forwardRegistry, forwarder)
	grpcServer := provideGRPCServer(executorServer, capabilityServer, dispatchServer, coherenceServer, server)
	health := NewHealth()
	httpServer := NewHTTPServer(cfg, health)
	serverWorkerComponent := provideWorkerComponent(runtime)
	ledgerCycle := provideCycle(cfg, store, dispatcher, eventBus, metrics)
	taskNotifier, cleanup3 := provideTaskNotifier(cfg)
	group := provideSchedulerGroup(cfg, ledgerCycle, coherenceStore, taskNotifier, metrics)
	serverSchedulerComponent := provideSchedulerComponent(group)
	channelProbe := provideChannelProbe(data)
	reconciler := provideReconciler(cfg, store, cacheviewView, channelProbe, metrics)
	serverReconcileComponent := provideReconcileComponent(reconciler)
	coherenceSyncer := provideCoherenceSyncer(cfg, coherenceStore, cache, dialer, metrics)
	serverSyncerComponent := provideSyncerComponent(coherenceSyncer)
	coherencePuller := provideCoherencePuller(cfg, coherenceStore, cache, dialer, cacheviewView, metrics)
	serverPullerComponent := providePullerComponent(coherencePuller)
	factoryRegistry, err := provideFactoryRegistry(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	enqueuer := provideEnqueuer(store, snowflake, cfg)
	manager := provideFactoryManager(factoryRegistry, enqueuer)
	serverFactoryComponent := provideFactoryComponent(manager)
	runner := provideCollectorRunner(cfg, eventBus, collector, metrics)
	serverCollectorRunnerComponent := provideCollectorRunnerComponent(runner)
	v := provideComponents(cfg, cache, eventBus, serverWorkerComponent, serverSchedulerComponent, serverReconcileComponent, serverSyncerComponent, serverPullerComponent, serverFactoryComponent, serverCollectorRunnerComponent)
	app, err := provideApp(cfg, grpcServer, httpServer, v, forwardRegistry, dispatchServer, health)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// ProviderSet 是全部装配提供者（§15.1#1）。
var ProviderSet = wire.NewSet(

	provideMetrics,
	provideDialer,
	provideClusterView,
	provideClusterCache,
	provideEventBus,
	provideCacheView,
	dataOpen,

	provideStore,
	provideSnowflake,
	provideTaskRegistry,
	provideCodec,
	provideEnqueuer,
	provideFactoryRegistry,
	provideFactoryManager,
	provideFactoryComponent,

	provideCapabilityRegistry,
	provideHandlerRegistry,
	provideResultPublisher,
	provideWorkerRuntime,
	provideWorkerComponent,

	provideForwarder,
	provideForwardRegistry,
	provideForwardServer,
	provideDispatcher,
	provideDispatchServer,

	provideCoherenceStore,
	provideCoherenceServer,
	provideCoherenceSyncer,
	provideCoherencePuller,
	provideSyncerComponent,
	providePullerComponent,

	provideCollector,
	provideCollectorRunner,
	provideCollectorRunnerComponent,
	provideReconciler,
	provideReconcileComponent,
	provideChannelProbe,

	provideCycle,
	provideSchedulerGroup,
	provideSchedulerComponent,
	provideTaskNotifier,

	provideExecutorServer,
	provideCapabilityServer,
	provideGRPCServer,
	provideComponents,
	NewHealth,
	NewHTTPServer,
	provideApp,
)
