// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/improvtrace/stateflux/store/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/improvtrace/stateflux/store/ent/completed"
	"github.com/improvtrace/stateflux/store/ent/payload"
	"github.com/improvtrace/stateflux/store/ent/pending"
	"github.com/improvtrace/stateflux/store/ent/processing"
	"github.com/improvtrace/stateflux/store/ent/result"
	"github.com/improvtrace/stateflux/store/ent/schedulable"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Completed is the client for interacting with the Completed builders.
	Completed *CompletedClient
	// Payload is the client for interacting with the Payload builders.
	Payload *PayloadClient
	// Pending is the client for interacting with the Pending builders.
	Pending *PendingClient
	// Processing is the client for interacting with the Processing builders.
	Processing *ProcessingClient
	// Result is the client for interacting with the Result builders.
	Result *ResultClient
	// Schedulable is the client for interacting with the Schedulable builders.
	Schedulable *SchedulableClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Completed = NewCompletedClient(c.config)
	c.Payload = NewPayloadClient(c.config)
	c.Pending = NewPendingClient(c.config)
	c.Processing = NewProcessingClient(c.config)
	c.Result = NewResultClient(c.config)
	c.Schedulable = NewSchedulableClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Completed:   NewCompletedClient(cfg),
		Payload:     NewPayloadClient(cfg),
		Pending:     NewPendingClient(cfg),
		Processing:  NewProcessingClient(cfg),
		Result:      NewResultClient(cfg),
		Schedulable: NewSchedulableClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Completed:   NewCompletedClient(cfg),
		Payload:     NewPayloadClient(cfg),
		Pending:     NewPendingClient(cfg),
		Processing:  NewProcessingClient(cfg),
		Result:      NewResultClient(cfg),
		Schedulable: NewSchedulableClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Completed.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Completed, c.Payload, c.Pending, c.Processing, c.Result, c.Schedulable,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Completed, c.Payload, c.Pending, c.Processing, c.Result, c.Schedulable,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CompletedMutation:
		return c.Completed.mutate(ctx, m)
	case *PayloadMutation:
		return c.Payload.mutate(ctx, m)
	case *PendingMutation:
		return c.Pending.mutate(ctx, m)
	case *ProcessingMutation:
		return c.Processing.mutate(ctx, m)
	case *ResultMutation:
		return c.Result.mutate(ctx, m)
	case *SchedulableMutation:
		return c.Schedulable.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CompletedClient is a client for the Completed schema.
type CompletedClient struct {
	config
}

// NewCompletedClient returns a client for the Completed from the given config.
func NewCompletedClient(c config) *CompletedClient {
	return &CompletedClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `completed.Hooks(f(g(h())))`.
func (c *CompletedClient) Use(hooks ...Hook) {
	c.hooks.Completed = append(c.hooks.Completed, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `completed.Intercept(f(g(h())))`.
func (c *CompletedClient) Intercept(interceptors ...Interceptor) {
	c.inters.Completed = append(c.inters.Completed, interceptors...)
}

// Create returns a builder for creating a Completed entity.
func (c *CompletedClient) Create() *CompletedCreate {
	mutation := newCompletedMutation(c.config, OpCreate)
	return &CompletedCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Completed entities.
func (c *CompletedClient) CreateBulk(builders ...*CompletedCreate) *CompletedCreateBulk {
	return &CompletedCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CompletedClient) MapCreateBulk(slice any, setFunc func(*CompletedCreate, int)) *CompletedCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CompletedCreateBulk{err: fmt.Errorf("calling to CompletedClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CompletedCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CompletedCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Completed.
func (c *CompletedClient) Update() *CompletedUpdate {
	mutation := newCompletedMutation(c.config, OpUpdate)
	return &CompletedUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CompletedClient) UpdateOne(_m *Completed) *CompletedUpdateOne {
	mutation := newCompletedMutation(c.config, OpUpdateOne, withCompleted(_m))
	return &CompletedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CompletedClient) UpdateOneID(id int64) *CompletedUpdateOne {
	mutation := newCompletedMutation(c.config, OpUpdateOne, withCompletedID(id))
	return &CompletedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Completed.
func (c *CompletedClient) Delete() *CompletedDelete {
	mutation := newCompletedMutation(c.config, OpDelete)
	return &CompletedDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CompletedClient) DeleteOne(_m *Completed) *CompletedDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CompletedClient) DeleteOneID(id int64) *CompletedDeleteOne {
	builder := c.Delete().Where(completed.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CompletedDeleteOne{builder}
}

// Query returns a query builder for Completed.
func (c *CompletedClient) Query() *CompletedQuery {
	return &CompletedQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCompleted},
		inters: c.Interceptors(),
	}
}

// Get returns a Completed entity by its id.
func (c *CompletedClient) Get(ctx context.Context, id int64) (*Completed, error) {
	return c.Query().Where(completed.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CompletedClient) GetX(ctx context.Context, id int64) *Completed {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CompletedClient) Hooks() []Hook {
	return c.hooks.Completed
}

// Interceptors returns the client interceptors.
func (c *CompletedClient) Interceptors() []Interceptor {
	return c.inters.Completed
}

func (c *CompletedClient) mutate(ctx context.Context, m *CompletedMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CompletedCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CompletedUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CompletedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CompletedDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Completed mutation op: %q", m.Op())
	}
}

// PayloadClient is a client for the Payload schema.
type PayloadClient struct {
	config
}

// NewPayloadClient returns a client for the Payload from the given config.
func NewPayloadClient(c config) *PayloadClient {
	return &PayloadClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `payload.Hooks(f(g(h())))`.
func (c *PayloadClient) Use(hooks ...Hook) {
	c.hooks.Payload = append(c.hooks.Payload, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `payload.Intercept(f(g(h())))`.
func (c *PayloadClient) Intercept(interceptors ...Interceptor) {
	c.inters.Payload = append(c.inters.Payload, interceptors...)
}

// Create returns a builder for creating a Payload entity.
func (c *PayloadClient) Create() *PayloadCreate {
	mutation := newPayloadMutation(c.config, OpCreate)
	return &PayloadCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Payload entities.
func (c *PayloadClient) CreateBulk(builders ...*PayloadCreate) *PayloadCreateBulk {
	return &PayloadCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PayloadClient) MapCreateBulk(slice any, setFunc func(*PayloadCreate, int)) *PayloadCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PayloadCreateBulk{err: fmt.Errorf("calling to PayloadClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PayloadCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PayloadCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Payload.
func (c *PayloadClient) Update() *PayloadUpdate {
	mutation := newPayloadMutation(c.config, OpUpdate)
	return &PayloadUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PayloadClient) UpdateOne(_m *Payload) *PayloadUpdateOne {
	mutation := newPayloadMutation(c.config, OpUpdateOne, withPayload(_m))
	return &PayloadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PayloadClient) UpdateOneID(id int64) *PayloadUpdateOne {
	mutation := newPayloadMutation(c.config, OpUpdateOne, withPayloadID(id))
	return &PayloadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Payload.
func (c *PayloadClient) Delete() *PayloadDelete {
	mutation := newPayloadMutation(c.config, OpDelete)
	return &PayloadDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PayloadClient) DeleteOne(_m *Payload) *PayloadDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PayloadClient) DeleteOneID(id int64) *PayloadDeleteOne {
	builder := c.Delete().Where(payload.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PayloadDeleteOne{builder}
}

// Query returns a query builder for Payload.
func (c *PayloadClient) Query() *PayloadQuery {
	return &PayloadQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePayload},
		inters: c.Interceptors(),
	}
}

// Get returns a Payload entity by its id.
func (c *PayloadClient) Get(ctx context.Context, id int64) (*Payload, error) {
	return c.Query().Where(payload.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PayloadClient) GetX(ctx context.Context, id int64) *Payload {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PayloadClient) Hooks() []Hook {
	return c.hooks.Payload
}

// Interceptors returns the client interceptors.
func (c *PayloadClient) Interceptors() []Interceptor {
	return c.inters.Payload
}

func (c *PayloadClient) mutate(ctx context.Context, m *PayloadMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PayloadCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PayloadUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PayloadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PayloadDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Payload mutation op: %q", m.Op())
	}
}

// PendingClient is a client for the Pending schema.
type PendingClient struct {
	config
}

// NewPendingClient returns a client for the Pending from the given config.
func NewPendingClient(c config) *PendingClient {
	return &PendingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pending.Hooks(f(g(h())))`.
func (c *PendingClient) Use(hooks ...Hook) {
	c.hooks.Pending = append(c.hooks.Pending, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pending.Intercept(f(g(h())))`.
func (c *PendingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pending = append(c.inters.Pending, interceptors...)
}

// Create returns a builder for creating a Pending entity.
func (c *PendingClient) Create() *PendingCreate {
	mutation := newPendingMutation(c.config, OpCreate)
	return &PendingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pending entities.
func (c *PendingClient) CreateBulk(builders ...*PendingCreate) *PendingCreateBulk {
	return &PendingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PendingClient) MapCreateBulk(slice any, setFunc func(*PendingCreate, int)) *PendingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PendingCreateBulk{err: fmt.Errorf("calling to PendingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PendingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PendingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pending.
func (c *PendingClient) Update() *PendingUpdate {
	mutation := newPendingMutation(c.config, OpUpdate)
	return &PendingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PendingClient) UpdateOne(_m *Pending) *PendingUpdateOne {
	mutation := newPendingMutation(c.config, OpUpdateOne, withPending(_m))
	return &PendingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PendingClient) UpdateOneID(id int64) *PendingUpdateOne {
	mutation := newPendingMutation(c.config, OpUpdateOne, withPendingID(id))
	return &PendingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pending.
func (c *PendingClient) Delete() *PendingDelete {
	mutation := newPendingMutation(c.config, OpDelete)
	return &PendingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PendingClient) DeleteOne(_m *Pending) *PendingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PendingClient) DeleteOneID(id int64) *PendingDeleteOne {
	builder := c.Delete().Where(pending.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PendingDeleteOne{builder}
}

// Query returns a query builder for Pending.
func (c *PendingClient) Query() *PendingQuery {
	return &PendingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePending},
		inters: c.Interceptors(),
	}
}

// Get returns a Pending entity by its id.
func (c *PendingClient) Get(ctx context.Context, id int64) (*Pending, error) {
	return c.Query().Where(pending.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PendingClient) GetX(ctx context.Context, id int64) *Pending {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PendingClient) Hooks() []Hook {
	return c.hooks.Pending
}

// Interceptors returns the client interceptors.
func (c *PendingClient) Interceptors() []Interceptor {
	return c.inters.Pending
}

func (c *PendingClient) mutate(ctx context.Context, m *PendingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PendingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PendingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PendingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PendingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pending mutation op: %q", m.Op())
	}
}

// ProcessingClient is a client for the Processing schema.
type ProcessingClient struct {
	config
}

// NewProcessingClient returns a client for the Processing from the given config.
func NewProcessingClient(c config) *ProcessingClient {
	return &ProcessingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `processing.Hooks(f(g(h())))`.
func (c *ProcessingClient) Use(hooks ...Hook) {
	c.hooks.Processing = append(c.hooks.Processing, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `processing.Intercept(f(g(h())))`.
func (c *ProcessingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Processing = append(c.inters.Processing, interceptors...)
}

// Create returns a builder for creating a Processing entity.
func (c *ProcessingClient) Create() *ProcessingCreate {
	mutation := newProcessingMutation(c.config, OpCreate)
	return &ProcessingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Processing entities.
func (c *ProcessingClient) CreateBulk(builders ...*ProcessingCreate) *ProcessingCreateBulk {
	return &ProcessingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProcessingClient) MapCreateBulk(slice any, setFunc func(*ProcessingCreate, int)) *ProcessingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProcessingCreateBulk{err: fmt.Errorf("calling to ProcessingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProcessingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProcessingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Processing.
func (c *ProcessingClient) Update() *ProcessingUpdate {
	mutation := newProcessingMutation(c.config, OpUpdate)
	return &ProcessingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProcessingClient) UpdateOne(_m *Processing) *ProcessingUpdateOne {
	mutation := newProcessingMutation(c.config, OpUpdateOne, withProcessing(_m))
	return &ProcessingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProcessingClient) UpdateOneID(id int64) *ProcessingUpdateOne {
	mutation := newProcessingMutation(c.config, OpUpdateOne, withProcessingID(id))
	return &ProcessingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Processing.
func (c *ProcessingClient) Delete() *ProcessingDelete {
	mutation := newProcessingMutation(c.config, OpDelete)
	return &ProcessingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProcessingClient) DeleteOne(_m *Processing) *ProcessingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProcessingClient) DeleteOneID(id int64) *ProcessingDeleteOne {
	builder := c.Delete().Where(processing.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProcessingDeleteOne{builder}
}

// Query returns a query builder for Processing.
func (c *ProcessingClient) Query() *ProcessingQuery {
	return &ProcessingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProcessing},
		inters: c.Interceptors(),
	}
}

// Get returns a Processing entity by its id.
func (c *ProcessingClient) Get(ctx context.Context, id int64) (*Processing, error) {
	return c.Query().Where(processing.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProcessingClient) GetX(ctx context.Context, id int64) *Processing {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProcessingClient) Hooks() []Hook {
	return c.hooks.Processing
}

// Interceptors returns the client interceptors.
func (c *ProcessingClient) Interceptors() []Interceptor {
	return c.inters.Processing
}

func (c *ProcessingClient) mutate(ctx context.Context, m *ProcessingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProcessingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProcessingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProcessingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProcessingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Processing mutation op: %q", m.Op())
	}
}

// ResultClient is a client for the Result schema.
type ResultClient struct {
	config
}

// NewResultClient returns a client for the Result from the given config.
func NewResultClient(c config) *ResultClient {
	return &ResultClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `result.Hooks(f(g(h())))`.
func (c *ResultClient) Use(hooks ...Hook) {
	c.hooks.Result = append(c.hooks.Result, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `result.Intercept(f(g(h())))`.
func (c *ResultClient) Intercept(interceptors ...Interceptor) {
	c.inters.Result = append(c.inters.Result, interceptors...)
}

// Create returns a builder for creating a Result entity.
func (c *ResultClient) Create() *ResultCreate {
	mutation := newResultMutation(c.config, OpCreate)
	return &ResultCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Result entities.
func (c *ResultClient) CreateBulk(builders ...*ResultCreate) *ResultCreateBulk {
	return &ResultCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ResultClient) MapCreateBulk(slice any, setFunc func(*ResultCreate, int)) *ResultCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ResultCreateBulk{err: fmt.Errorf("calling to ResultClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ResultCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ResultCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Result.
func (c *ResultClient) Update() *ResultUpdate {
	mutation := newResultMutation(c.config, OpUpdate)
	return &ResultUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ResultClient) UpdateOne(_m *Result) *ResultUpdateOne {
	mutation := newResultMutation(c.config, OpUpdateOne, withResult(_m))
	return &ResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ResultClient) UpdateOneID(id int64) *ResultUpdateOne {
	mutation := newResultMutation(c.config, OpUpdateOne, withResultID(id))
	return &ResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Result.
func (c *ResultClient) Delete() *ResultDelete {
	mutation := newResultMutation(c.config, OpDelete)
	return &ResultDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ResultClient) DeleteOne(_m *Result) *ResultDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ResultClient) DeleteOneID(id int64) *ResultDeleteOne {
	builder := c.Delete().Where(result.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ResultDeleteOne{builder}
}

// Query returns a query builder for Result.
func (c *ResultClient) Query() *ResultQuery {
	return &ResultQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeResult},
		inters: c.Interceptors(),
	}
}

// Get returns a Result entity by its id.
func (c *ResultClient) Get(ctx context.Context, id int64) (*Result, error) {
	return c.Query().Where(result.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ResultClient) GetX(ctx context.Context, id int64) *Result {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ResultClient) Hooks() []Hook {
	return c.hooks.Result
}

// Interceptors returns the client interceptors.
func (c *ResultClient) Interceptors() []Interceptor {
	return c.inters.Result
}

func (c *ResultClient) mutate(ctx context.Context, m *ResultMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ResultCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ResultUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ResultDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Result mutation op: %q", m.Op())
	}
}

// SchedulableClient is a client for the Schedulable schema.
type SchedulableClient struct {
	config
}

// NewSchedulableClient returns a client for the Schedulable from the given config.
func NewSchedulableClient(c config) *SchedulableClient {
	return &SchedulableClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schedulable.Hooks(f(g(h())))`.
func (c *SchedulableClient) Use(hooks ...Hook) {
	c.hooks.Schedulable = append(c.hooks.Schedulable, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schedulable.Intercept(f(g(h())))`.
func (c *SchedulableClient) Intercept(interceptors ...Interceptor) {
	c.inters.Schedulable = append(c.inters.Schedulable, interceptors...)
}

// Create returns a builder for creating a Schedulable entity.
func (c *SchedulableClient) Create() *SchedulableCreate {
	mutation := newSchedulableMutation(c.config, OpCreate)
	return &SchedulableCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Schedulable entities.
func (c *SchedulableClient) CreateBulk(builders ...*SchedulableCreate) *SchedulableCreateBulk {
	return &SchedulableCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SchedulableClient) MapCreateBulk(slice any, setFunc func(*SchedulableCreate, int)) *SchedulableCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SchedulableCreateBulk{err: fmt.Errorf("calling to SchedulableClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SchedulableCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SchedulableCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Schedulable.
func (c *SchedulableClient) Update() *SchedulableUpdate {
	mutation := newSchedulableMutation(c.config, OpUpdate)
	return &SchedulableUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SchedulableClient) UpdateOne(_m *Schedulable) *SchedulableUpdateOne {
	mutation := newSchedulableMutation(c.config, OpUpdateOne, withSchedulable(_m))
	return &SchedulableUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SchedulableClient) UpdateOneID(id int64) *SchedulableUpdateOne {
	mutation := newSchedulableMutation(c.config, OpUpdateOne, withSchedulableID(id))
	return &SchedulableUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Schedulable.
func (c *SchedulableClient) Delete() *SchedulableDelete {
	mutation := newSchedulableMutation(c.config, OpDelete)
	return &SchedulableDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SchedulableClient) DeleteOne(_m *Schedulable) *SchedulableDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SchedulableClient) DeleteOneID(id int64) *SchedulableDeleteOne {
	builder := c.Delete().Where(schedulable.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SchedulableDeleteOne{builder}
}

// Query returns a query builder for Schedulable.
func (c *SchedulableClient) Query() *SchedulableQuery {
	return &SchedulableQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchedulable},
		inters: c.Interceptors(),
	}
}

// Get returns a Schedulable entity by its id.
func (c *SchedulableClient) Get(ctx context.Context, id int64) (*Schedulable, error) {
	return c.Query().Where(schedulable.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SchedulableClient) GetX(ctx context.Context, id int64) *Schedulable {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SchedulableClient) Hooks() []Hook {
	return c.hooks.Schedulable
}

// Interceptors returns the client interceptors.
func (c *SchedulableClient) Interceptors() []Interceptor {
	return c.inters.Schedulable
}

func (c *SchedulableClient) mutate(ctx context.Context, m *SchedulableMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SchedulableCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SchedulableUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SchedulableUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SchedulableDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Schedulable mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Completed, Payload, Pending, Processing, Result, Schedulable []ent.Hook
	}
	inters struct {
		Completed, Payload, Pending, Processing, Result, Schedulable []ent.Interceptor
	}
)
