// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/improvtrace/stateflux/store/ent/completed"
	"github.com/improvtrace/stateflux/store/ent/predicate"
)

// CompletedUpdate is the builder for updating Completed entities.
type CompletedUpdate struct {
	config
	hooks    []Hook
	mutation *CompletedMutation
}

// Where appends a list predicates to the CompletedUpdate builder.
func (_u *CompletedUpdate) Where(ps ...predicate.Completed) *CompletedUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *CompletedUpdate) SetType(v string) *CompletedUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableType(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CompletedUpdate) SetPriority(v string) *CompletedUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillablePriority(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *CompletedUpdate) SetExecMode(v string) *CompletedUpdate {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableExecMode(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *CompletedUpdate) SetRunAt(v time.Time) *CompletedUpdate {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableRunAt(v *time.Time) *CompletedUpdate {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *CompletedUpdate) SetTimeoutMs(v int64) *CompletedUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableTimeoutMs(v *int64) *CompletedUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *CompletedUpdate) AddTimeoutMs(v int64) *CompletedUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *CompletedUpdate) SetMaxAttempts(v int32) *CompletedUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableMaxAttempts(v *int32) *CompletedUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *CompletedUpdate) AddMaxAttempts(v int32) *CompletedUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *CompletedUpdate) SetAttempts(v int64) *CompletedUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableAttempts(v *int64) *CompletedUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *CompletedUpdate) AddAttempts(v int64) *CompletedUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *CompletedUpdate) SetOwnerNode(v string) *CompletedUpdate {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableOwnerNode(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *CompletedUpdate) SetError(v string) *CompletedUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableError(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *CompletedUpdate) SetIdempotencyKey(v string) *CompletedUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableIdempotencyKey(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *CompletedUpdate) SetBatchID(v string) *CompletedUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableBatchID(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *CompletedUpdate) SetCallback(v jsontext.Value) *CompletedUpdate {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *CompletedUpdate) AppendCallback(v jsontext.Value) *CompletedUpdate {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *CompletedUpdate) ClearCallback() *CompletedUpdate {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *CompletedUpdate) SetParentTaskID(v int64) *CompletedUpdate {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableParentTaskID(v *int64) *CompletedUpdate {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *CompletedUpdate) AddParentTaskID(v int64) *CompletedUpdate {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompletedUpdate) SetUpdatedAt(v time.Time) *CompletedUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *CompletedUpdate) SetOutcome(v string) *CompletedUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableOutcome(v *string) *CompletedUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *CompletedUpdate) SetPayload(v jsontext.Value) *CompletedUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *CompletedUpdate) AppendPayload(v jsontext.Value) *CompletedUpdate {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *CompletedUpdate) ClearPayload() *CompletedUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CompletedUpdate) SetCompletedAt(v time.Time) *CompletedUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CompletedUpdate) SetNillableCompletedAt(v *time.Time) *CompletedUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// Mutation returns the CompletedMutation object of the builder.
func (_u *CompletedUpdate) Mutation() *CompletedMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompletedUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompletedUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompletedUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompletedUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompletedUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := completed.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompletedUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := completed.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Completed.type": %w`, err)}
		}
	}
	return nil
}

func (_u *CompletedUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(completed.Table, completed.Columns, sqlgraph.NewFieldSpec(completed.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(completed.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(completed.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(completed.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(completed.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(completed.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(completed.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(completed.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(completed.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(completed.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(completed.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(completed.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(completed.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(completed.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(completed.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(completed.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, completed.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(completed.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(completed.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(completed.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(completed.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(completed.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(completed.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, completed.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(completed.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(completed.FieldCompletedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{completed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompletedUpdateOne is the builder for updating a single Completed entity.
type CompletedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompletedMutation
}

// SetType sets the "type" field.
func (_u *CompletedUpdateOne) SetType(v string) *CompletedUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableType(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CompletedUpdateOne) SetPriority(v string) *CompletedUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillablePriority(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *CompletedUpdateOne) SetExecMode(v string) *CompletedUpdateOne {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableExecMode(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *CompletedUpdateOne) SetRunAt(v time.Time) *CompletedUpdateOne {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableRunAt(v *time.Time) *CompletedUpdateOne {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *CompletedUpdateOne) SetTimeoutMs(v int64) *CompletedUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableTimeoutMs(v *int64) *CompletedUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *CompletedUpdateOne) AddTimeoutMs(v int64) *CompletedUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *CompletedUpdateOne) SetMaxAttempts(v int32) *CompletedUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableMaxAttempts(v *int32) *CompletedUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *CompletedUpdateOne) AddMaxAttempts(v int32) *CompletedUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *CompletedUpdateOne) SetAttempts(v int64) *CompletedUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableAttempts(v *int64) *CompletedUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *CompletedUpdateOne) AddAttempts(v int64) *CompletedUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *CompletedUpdateOne) SetOwnerNode(v string) *CompletedUpdateOne {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableOwnerNode(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *CompletedUpdateOne) SetError(v string) *CompletedUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableError(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *CompletedUpdateOne) SetIdempotencyKey(v string) *CompletedUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableIdempotencyKey(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *CompletedUpdateOne) SetBatchID(v string) *CompletedUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableBatchID(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *CompletedUpdateOne) SetCallback(v jsontext.Value) *CompletedUpdateOne {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *CompletedUpdateOne) AppendCallback(v jsontext.Value) *CompletedUpdateOne {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *CompletedUpdateOne) ClearCallback() *CompletedUpdateOne {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *CompletedUpdateOne) SetParentTaskID(v int64) *CompletedUpdateOne {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableParentTaskID(v *int64) *CompletedUpdateOne {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *CompletedUpdateOne) AddParentTaskID(v int64) *CompletedUpdateOne {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompletedUpdateOne) SetUpdatedAt(v time.Time) *CompletedUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *CompletedUpdateOne) SetOutcome(v string) *CompletedUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableOutcome(v *string) *CompletedUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *CompletedUpdateOne) SetPayload(v jsontext.Value) *CompletedUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *CompletedUpdateOne) AppendPayload(v jsontext.Value) *CompletedUpdateOne {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *CompletedUpdateOne) ClearPayload() *CompletedUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CompletedUpdateOne) SetCompletedAt(v time.Time) *CompletedUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CompletedUpdateOne) SetNillableCompletedAt(v *time.Time) *CompletedUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// Mutation returns the CompletedMutation object of the builder.
func (_u *CompletedUpdateOne) Mutation() *CompletedMutation {
	return _u.mutation
}

// Where appends a list predicates to the CompletedUpdate builder.
func (_u *CompletedUpdateOne) Where(ps ...predicate.Completed) *CompletedUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompletedUpdateOne) Select(field string, fields ...string) *CompletedUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Completed entity.
func (_u *CompletedUpdateOne) Save(ctx context.Context) (*Completed, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompletedUpdateOne) SaveX(ctx context.Context) *Completed {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompletedUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompletedUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompletedUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := completed.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompletedUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := completed.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Completed.type": %w`, err)}
		}
	}
	return nil
}

func (_u *CompletedUpdateOne) sqlSave(ctx context.Context) (_node *Completed, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(completed.Table, completed.Columns, sqlgraph.NewFieldSpec(completed.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Completed.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, completed.FieldID)
		for _, f := range fields {
			if !completed.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != completed.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(completed.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(completed.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(completed.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(completed.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(completed.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(completed.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(completed.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(completed.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(completed.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(completed.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(completed.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(completed.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(completed.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(completed.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(completed.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, completed.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(completed.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(completed.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(completed.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(completed.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(completed.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(completed.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, completed.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(completed.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(completed.FieldCompletedAt, field.TypeTime, value)
	}
	_node = &Completed{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{completed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
