// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/improvtrace/stateflux/store/ent/payload"
	"github.com/improvtrace/stateflux/store/ent/predicate"
)

// PayloadUpdate is the builder for updating Payload entities.
type PayloadUpdate struct {
	config
	hooks    []Hook
	mutation *PayloadMutation
}

// Where appends a list predicates to the PayloadUpdate builder.
func (_u *PayloadUpdate) Where(ps ...predicate.Payload) *PayloadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *PayloadUpdate) SetPayload(v jsontext.Value) *PayloadUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *PayloadUpdate) AppendPayload(v jsontext.Value) *PayloadUpdate {
	_u.mutation.AppendPayload(v)
	return _u
}

// Mutation returns the PayloadMutation object of the builder.
func (_u *PayloadUpdate) Mutation() *PayloadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PayloadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PayloadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PayloadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(payload.Table, payload.Columns, sqlgraph.NewFieldSpec(payload.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(payload.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, payload.FieldPayload, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PayloadUpdateOne is the builder for updating a single Payload entity.
type PayloadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PayloadMutation
}

// SetPayload sets the "payload" field.
func (_u *PayloadUpdateOne) SetPayload(v jsontext.Value) *PayloadUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *PayloadUpdateOne) AppendPayload(v jsontext.Value) *PayloadUpdateOne {
	_u.mutation.AppendPayload(v)
	return _u
}

// Mutation returns the PayloadMutation object of the builder.
func (_u *PayloadUpdateOne) Mutation() *PayloadMutation {
	return _u.mutation
}

// Where appends a list predicates to the PayloadUpdate builder.
func (_u *PayloadUpdateOne) Where(ps ...predicate.Payload) *PayloadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PayloadUpdateOne) Select(field string, fields ...string) *PayloadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payload entity.
func (_u *PayloadUpdateOne) Save(ctx context.Context) (*Payload, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PayloadUpdateOne) SaveX(ctx context.Context) *Payload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PayloadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PayloadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PayloadUpdateOne) sqlSave(ctx context.Context) (_node *Payload, err error) {
	_spec := sqlgraph.NewUpdateSpec(payload.Table, payload.Columns, sqlgraph.NewFieldSpec(payload.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payload.FieldID)
		for _, f := range fields {
			if !payload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(payload.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, payload.FieldPayload, value)
		})
	}
	_node = &Payload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
