// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/improvtrace/stateflux/store/ent/pending"
	"github.com/improvtrace/stateflux/store/ent/predicate"
)

// PendingUpdate is the builder for updating Pending entities.
type PendingUpdate struct {
	config
	hooks    []Hook
	mutation *PendingMutation
}

// Where appends a list predicates to the PendingUpdate builder.
func (_u *PendingUpdate) Where(ps ...predicate.Pending) *PendingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *PendingUpdate) SetType(v string) *PendingUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableType(v *string) *PendingUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PendingUpdate) SetPriority(v string) *PendingUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PendingUpdate) SetNillablePriority(v *string) *PendingUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *PendingUpdate) SetExecMode(v string) *PendingUpdate {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableExecMode(v *string) *PendingUpdate {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *PendingUpdate) SetRunAt(v time.Time) *PendingUpdate {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableRunAt(v *time.Time) *PendingUpdate {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *PendingUpdate) SetTimeoutMs(v int64) *PendingUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableTimeoutMs(v *int64) *PendingUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *PendingUpdate) AddTimeoutMs(v int64) *PendingUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *PendingUpdate) SetMaxAttempts(v int32) *PendingUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableMaxAttempts(v *int32) *PendingUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *PendingUpdate) AddMaxAttempts(v int32) *PendingUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *PendingUpdate) SetAttempts(v int64) *PendingUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableAttempts(v *int64) *PendingUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *PendingUpdate) AddAttempts(v int64) *PendingUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *PendingUpdate) SetOwnerNode(v string) *PendingUpdate {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableOwnerNode(v *string) *PendingUpdate {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *PendingUpdate) SetError(v string) *PendingUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableError(v *string) *PendingUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *PendingUpdate) SetIdempotencyKey(v string) *PendingUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableIdempotencyKey(v *string) *PendingUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *PendingUpdate) SetBatchID(v string) *PendingUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableBatchID(v *string) *PendingUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *PendingUpdate) SetCallback(v jsontext.Value) *PendingUpdate {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *PendingUpdate) AppendCallback(v jsontext.Value) *PendingUpdate {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *PendingUpdate) ClearCallback() *PendingUpdate {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *PendingUpdate) SetParentTaskID(v int64) *PendingUpdate {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *PendingUpdate) SetNillableParentTaskID(v *int64) *PendingUpdate {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *PendingUpdate) AddParentTaskID(v int64) *PendingUpdate {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PendingUpdate) SetUpdatedAt(v time.Time) *PendingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PendingMutation object of the builder.
func (_u *PendingUpdate) Mutation() *PendingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PendingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PendingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PendingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PendingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PendingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pending.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PendingUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := pending.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Pending.type": %w`, err)}
		}
	}
	return nil
}

func (_u *PendingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pending.Table, pending.Columns, sqlgraph.NewFieldSpec(pending.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pending.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pending.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(pending.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(pending.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(pending.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(pending.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(pending.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(pending.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(pending.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(pending.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(pending.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(pending.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(pending.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(pending.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(pending.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pending.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(pending.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(pending.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(pending.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pending.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pending.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PendingUpdateOne is the builder for updating a single Pending entity.
type PendingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PendingMutation
}

// SetType sets the "type" field.
func (_u *PendingUpdateOne) SetType(v string) *PendingUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableType(v *string) *PendingUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PendingUpdateOne) SetPriority(v string) *PendingUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillablePriority(v *string) *PendingUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *PendingUpdateOne) SetExecMode(v string) *PendingUpdateOne {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableExecMode(v *string) *PendingUpdateOne {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *PendingUpdateOne) SetRunAt(v time.Time) *PendingUpdateOne {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableRunAt(v *time.Time) *PendingUpdateOne {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *PendingUpdateOne) SetTimeoutMs(v int64) *PendingUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableTimeoutMs(v *int64) *PendingUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *PendingUpdateOne) AddTimeoutMs(v int64) *PendingUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *PendingUpdateOne) SetMaxAttempts(v int32) *PendingUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableMaxAttempts(v *int32) *PendingUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *PendingUpdateOne) AddMaxAttempts(v int32) *PendingUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *PendingUpdateOne) SetAttempts(v int64) *PendingUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableAttempts(v *int64) *PendingUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *PendingUpdateOne) AddAttempts(v int64) *PendingUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *PendingUpdateOne) SetOwnerNode(v string) *PendingUpdateOne {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableOwnerNode(v *string) *PendingUpdateOne {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *PendingUpdateOne) SetError(v string) *PendingUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableError(v *string) *PendingUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *PendingUpdateOne) SetIdempotencyKey(v string) *PendingUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableIdempotencyKey(v *string) *PendingUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *PendingUpdateOne) SetBatchID(v string) *PendingUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableBatchID(v *string) *PendingUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *PendingUpdateOne) SetCallback(v jsontext.Value) *PendingUpdateOne {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *PendingUpdateOne) AppendCallback(v jsontext.Value) *PendingUpdateOne {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *PendingUpdateOne) ClearCallback() *PendingUpdateOne {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *PendingUpdateOne) SetParentTaskID(v int64) *PendingUpdateOne {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *PendingUpdateOne) SetNillableParentTaskID(v *int64) *PendingUpdateOne {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *PendingUpdateOne) AddParentTaskID(v int64) *PendingUpdateOne {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PendingUpdateOne) SetUpdatedAt(v time.Time) *PendingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PendingMutation object of the builder.
func (_u *PendingUpdateOne) Mutation() *PendingMutation {
	return _u.mutation
}

// Where appends a list predicates to the PendingUpdate builder.
func (_u *PendingUpdateOne) Where(ps ...predicate.Pending) *PendingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PendingUpdateOne) Select(field string, fields ...string) *PendingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pending entity.
func (_u *PendingUpdateOne) Save(ctx context.Context) (*Pending, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PendingUpdateOne) SaveX(ctx context.Context) *Pending {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PendingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PendingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PendingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pending.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PendingUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := pending.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Pending.type": %w`, err)}
		}
	}
	return nil
}

func (_u *PendingUpdateOne) sqlSave(ctx context.Context) (_node *Pending, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pending.Table, pending.Columns, sqlgraph.NewFieldSpec(pending.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pending.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pending.FieldID)
		for _, f := range fields {
			if !pending.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pending.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pending.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pending.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(pending.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(pending.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(pending.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(pending.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(pending.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(pending.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(pending.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(pending.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(pending.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(pending.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(pending.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(pending.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(pending.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pending.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(pending.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(pending.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(pending.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pending.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Pending{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pending.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
