// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/improvtrace/stateflux/store/ent/predicate"
	"github.com/improvtrace/stateflux/store/ent/processing"
)

// ProcessingUpdate is the builder for updating Processing entities.
type ProcessingUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessingMutation
}

// Where appends a list predicates to the ProcessingUpdate builder.
func (_u *ProcessingUpdate) Where(ps ...predicate.Processing) *ProcessingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *ProcessingUpdate) SetType(v string) *ProcessingUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableType(v *string) *ProcessingUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProcessingUpdate) SetPriority(v string) *ProcessingUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillablePriority(v *string) *ProcessingUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *ProcessingUpdate) SetExecMode(v string) *ProcessingUpdate {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableExecMode(v *string) *ProcessingUpdate {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *ProcessingUpdate) SetRunAt(v time.Time) *ProcessingUpdate {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableRunAt(v *time.Time) *ProcessingUpdate {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *ProcessingUpdate) SetTimeoutMs(v int64) *ProcessingUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableTimeoutMs(v *int64) *ProcessingUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *ProcessingUpdate) AddTimeoutMs(v int64) *ProcessingUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *ProcessingUpdate) SetMaxAttempts(v int32) *ProcessingUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableMaxAttempts(v *int32) *ProcessingUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *ProcessingUpdate) AddMaxAttempts(v int32) *ProcessingUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *ProcessingUpdate) SetAttempts(v int64) *ProcessingUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableAttempts(v *int64) *ProcessingUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *ProcessingUpdate) AddAttempts(v int64) *ProcessingUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *ProcessingUpdate) SetOwnerNode(v string) *ProcessingUpdate {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableOwnerNode(v *string) *ProcessingUpdate {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *ProcessingUpdate) SetError(v string) *ProcessingUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableError(v *string) *ProcessingUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ProcessingUpdate) SetIdempotencyKey(v string) *ProcessingUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableIdempotencyKey(v *string) *ProcessingUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *ProcessingUpdate) SetBatchID(v string) *ProcessingUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableBatchID(v *string) *ProcessingUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *ProcessingUpdate) SetCallback(v jsontext.Value) *ProcessingUpdate {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *ProcessingUpdate) AppendCallback(v jsontext.Value) *ProcessingUpdate {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *ProcessingUpdate) ClearCallback() *ProcessingUpdate {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *ProcessingUpdate) SetParentTaskID(v int64) *ProcessingUpdate {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *ProcessingUpdate) SetNillableParentTaskID(v *int64) *ProcessingUpdate {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *ProcessingUpdate) AddParentTaskID(v int64) *ProcessingUpdate {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProcessingUpdate) SetUpdatedAt(v time.Time) *ProcessingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProcessingMutation object of the builder.
func (_u *ProcessingUpdate) Mutation() *ProcessingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProcessingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProcessingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := processing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProcessingUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := processing.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Processing.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProcessingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(processing.Table, processing.Columns, sqlgraph.NewFieldSpec(processing.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(processing.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(processing.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(processing.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(processing.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(processing.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(processing.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(processing.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(processing.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(processing.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(processing.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(processing.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(processing.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(processing.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(processing.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(processing.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, processing.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(processing.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(processing.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(processing.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(processing.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProcessingUpdateOne is the builder for updating a single Processing entity.
type ProcessingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessingMutation
}

// SetType sets the "type" field.
func (_u *ProcessingUpdateOne) SetType(v string) *ProcessingUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableType(v *string) *ProcessingUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProcessingUpdateOne) SetPriority(v string) *ProcessingUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillablePriority(v *string) *ProcessingUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *ProcessingUpdateOne) SetExecMode(v string) *ProcessingUpdateOne {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableExecMode(v *string) *ProcessingUpdateOne {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *ProcessingUpdateOne) SetRunAt(v time.Time) *ProcessingUpdateOne {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableRunAt(v *time.Time) *ProcessingUpdateOne {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *ProcessingUpdateOne) SetTimeoutMs(v int64) *ProcessingUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableTimeoutMs(v *int64) *ProcessingUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *ProcessingUpdateOne) AddTimeoutMs(v int64) *ProcessingUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *ProcessingUpdateOne) SetMaxAttempts(v int32) *ProcessingUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableMaxAttempts(v *int32) *ProcessingUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *ProcessingUpdateOne) AddMaxAttempts(v int32) *ProcessingUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *ProcessingUpdateOne) SetAttempts(v int64) *ProcessingUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableAttempts(v *int64) *ProcessingUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *ProcessingUpdateOne) AddAttempts(v int64) *ProcessingUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *ProcessingUpdateOne) SetOwnerNode(v string) *ProcessingUpdateOne {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableOwnerNode(v *string) *ProcessingUpdateOne {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *ProcessingUpdateOne) SetError(v string) *ProcessingUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableError(v *string) *ProcessingUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ProcessingUpdateOne) SetIdempotencyKey(v string) *ProcessingUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableIdempotencyKey(v *string) *ProcessingUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *ProcessingUpdateOne) SetBatchID(v string) *ProcessingUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableBatchID(v *string) *ProcessingUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *ProcessingUpdateOne) SetCallback(v jsontext.Value) *ProcessingUpdateOne {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *ProcessingUpdateOne) AppendCallback(v jsontext.Value) *ProcessingUpdateOne {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *ProcessingUpdateOne) ClearCallback() *ProcessingUpdateOne {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *ProcessingUpdateOne) SetParentTaskID(v int64) *ProcessingUpdateOne {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *ProcessingUpdateOne) SetNillableParentTaskID(v *int64) *ProcessingUpdateOne {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *ProcessingUpdateOne) AddParentTaskID(v int64) *ProcessingUpdateOne {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProcessingUpdateOne) SetUpdatedAt(v time.Time) *ProcessingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProcessingMutation object of the builder.
func (_u *ProcessingUpdateOne) Mutation() *ProcessingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProcessingUpdate builder.
func (_u *ProcessingUpdateOne) Where(ps ...predicate.Processing) *ProcessingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProcessingUpdateOne) Select(field string, fields ...string) *ProcessingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Processing entity.
func (_u *ProcessingUpdateOne) Save(ctx context.Context) (*Processing, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessingUpdateOne) SaveX(ctx context.Context) *Processing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProcessingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := processing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProcessingUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := processing.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Processing.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProcessingUpdateOne) sqlSave(ctx context.Context) (_node *Processing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(processing.Table, processing.Columns, sqlgraph.NewFieldSpec(processing.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Processing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processing.FieldID)
		for _, f := range fields {
			if !processing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != processing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(processing.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(processing.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(processing.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(processing.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(processing.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(processing.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(processing.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(processing.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(processing.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(processing.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(processing.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(processing.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(processing.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(processing.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(processing.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, processing.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(processing.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(processing.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(processing.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(processing.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Processing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
