// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/improvtrace/stateflux/store/ent/completed"
	"github.com/improvtrace/stateflux/store/ent/payload"
	"github.com/improvtrace/stateflux/store/ent/pending"
	"github.com/improvtrace/stateflux/store/ent/processing"
	"github.com/improvtrace/stateflux/store/ent/result"
	"github.com/improvtrace/stateflux/store/ent/schedulable"
	"github.com/improvtrace/stateflux/store/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	completedMixin := schema.Completed{}.Mixin()
	completedMixinFields0 := completedMixin[0].Fields()
	_ = completedMixinFields0
	completedFields := schema.Completed{}.Fields()
	_ = completedFields
	// completedDescType is the schema descriptor for type field.
	completedDescType := completedMixinFields0[1].Descriptor()
	// completed.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	completed.TypeValidator = completedDescType.Validators[0].(func(string) error)
	// completedDescPriority is the schema descriptor for priority field.
	completedDescPriority := completedMixinFields0[2].Descriptor()
	// completed.DefaultPriority holds the default value on creation for the priority field.
	completed.DefaultPriority = completedDescPriority.Default.(string)
	// completedDescExecMode is the schema descriptor for exec_mode field.
	completedDescExecMode := completedMixinFields0[3].Descriptor()
	// completed.DefaultExecMode holds the default value on creation for the exec_mode field.
	completed.DefaultExecMode = completedDescExecMode.Default.(string)
	// completedDescTimeoutMs is the schema descriptor for timeout_ms field.
	completedDescTimeoutMs := completedMixinFields0[5].Descriptor()
	// completed.DefaultTimeoutMs holds the default value on creation for the timeout_ms field.
	completed.DefaultTimeoutMs = completedDescTimeoutMs.Default.(int64)
	// completedDescMaxAttempts is the schema descriptor for max_attempts field.
	completedDescMaxAttempts := completedMixinFields0[6].Descriptor()
	// completed.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	completed.DefaultMaxAttempts = completedDescMaxAttempts.Default.(int32)
	// completedDescAttempts is the schema descriptor for attempts field.
	completedDescAttempts := completedMixinFields0[7].Descriptor()
	// completed.DefaultAttempts holds the default value on creation for the attempts field.
	completed.DefaultAttempts = completedDescAttempts.Default.(int64)
	// completedDescOwnerNode is the schema descriptor for owner_node field.
	completedDescOwnerNode := completedMixinFields0[8].Descriptor()
	// completed.DefaultOwnerNode holds the default value on creation for the owner_node field.
	completed.DefaultOwnerNode = completedDescOwnerNode.Default.(string)
	// completedDescError is the schema descriptor for error field.
	completedDescError := completedMixinFields0[9].Descriptor()
	// completed.DefaultError holds the default value on creation for the error field.
	completed.DefaultError = completedDescError.Default.(string)
	// completedDescIdempotencyKey is the schema descriptor for idempotency_key field.
	completedDescIdempotencyKey := completedMixinFields0[10].Descriptor()
	// completed.DefaultIdempotencyKey holds the default value on creation for the idempotency_key field.
	completed.DefaultIdempotencyKey = completedDescIdempotencyKey.Default.(string)
	// completedDescBatchID is the schema descriptor for batch_id field.
	completedDescBatchID := completedMixinFields0[11].Descriptor()
	// completed.DefaultBatchID holds the default value on creation for the batch_id field.
	completed.DefaultBatchID = completedDescBatchID.Default.(string)
	// completedDescParentTaskID is the schema descriptor for parent_task_id field.
	completedDescParentTaskID := completedMixinFields0[13].Descriptor()
	// completed.DefaultParentTaskID holds the default value on creation for the parent_task_id field.
	completed.DefaultParentTaskID = completedDescParentTaskID.Default.(int64)
	// completedDescCreatedAt is the schema descriptor for created_at field.
	completedDescCreatedAt := completedMixinFields0[14].Descriptor()
	// completed.DefaultCreatedAt holds the default value on creation for the created_at field.
	completed.DefaultCreatedAt = completedDescCreatedAt.Default.(func() time.Time)
	// completedDescUpdatedAt is the schema descriptor for updated_at field.
	completedDescUpdatedAt := completedMixinFields0[15].Descriptor()
	// completed.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	completed.DefaultUpdatedAt = completedDescUpdatedAt.Default.(func() time.Time)
	// completed.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	completed.UpdateDefaultUpdatedAt = completedDescUpdatedAt.UpdateDefault.(func() time.Time)
	payloadFields := schema.Payload{}.Fields()
	_ = payloadFields
	// payloadDescCreatedAt is the schema descriptor for created_at field.
	payloadDescCreatedAt := payloadFields[2].Descriptor()
	// payload.DefaultCreatedAt holds the default value on creation for the created_at field.
	payload.DefaultCreatedAt = payloadDescCreatedAt.Default.(func() time.Time)
	pendingMixin := schema.Pending{}.Mixin()
	pendingMixinFields0 := pendingMixin[0].Fields()
	_ = pendingMixinFields0
	pendingFields := schema.Pending{}.Fields()
	_ = pendingFields
	// pendingDescType is the schema descriptor for type field.
	pendingDescType := pendingMixinFields0[1].Descriptor()
	// pending.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	pending.TypeValidator = pendingDescType.Validators[0].(func(string) error)
	// pendingDescPriority is the schema descriptor for priority field.
	pendingDescPriority := pendingMixinFields0[2].Descriptor()
	// pending.DefaultPriority holds the default value on creation for the priority field.
	pending.DefaultPriority = pendingDescPriority.Default.(string)
	// pendingDescExecMode is the schema descriptor for exec_mode field.
	pendingDescExecMode := pendingMixinFields0[3].Descriptor()
	// pending.DefaultExecMode holds the default value on creation for the exec_mode field.
	pending.DefaultExecMode = pendingDescExecMode.Default.(string)
	// pendingDescTimeoutMs is the schema descriptor for timeout_ms field.
	pendingDescTimeoutMs := pendingMixinFields0[5].Descriptor()
	// pending.DefaultTimeoutMs holds the default value on creation for the timeout_ms field.
	pending.DefaultTimeoutMs = pendingDescTimeoutMs.Default.(int64)
	// pendingDescMaxAttempts is the schema descriptor for max_attempts field.
	pendingDescMaxAttempts := pendingMixinFields0[6].Descriptor()
	// pending.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	pending.DefaultMaxAttempts = pendingDescMaxAttempts.Default.(int32)
	// pendingDescAttempts is the schema descriptor for attempts field.
	pendingDescAttempts := pendingMixinFields0[7].Descriptor()
	// pending.DefaultAttempts holds the default value on creation for the attempts field.
	pending.DefaultAttempts = pendingDescAttempts.Default.(int64)
	// pendingDescOwnerNode is the schema descriptor for owner_node field.
	pendingDescOwnerNode := pendingMixinFields0[8].Descriptor()
	// pending.DefaultOwnerNode holds the default value on creation for the owner_node field.
	pending.DefaultOwnerNode = pendingDescOwnerNode.Default.(string)
	// pendingDescError is the schema descriptor for error field.
	pendingDescError := pendingMixinFields0[9].Descriptor()
	// pending.DefaultError holds the default value on creation for the error field.
	pending.DefaultError = pendingDescError.Default.(string)
	// pendingDescIdempotencyKey is the schema descriptor for idempotency_key field.
	pendingDescIdempotencyKey := pendingMixinFields0[10].Descriptor()
	// pending.DefaultIdempotencyKey holds the default value on creation for the idempotency_key field.
	pending.DefaultIdempotencyKey = pendingDescIdempotencyKey.Default.(string)
	// pendingDescBatchID is the schema descriptor for batch_id field.
	pendingDescBatchID := pendingMixinFields0[11].Descriptor()
	// pending.DefaultBatchID holds the default value on creation for the batch_id field.
	pending.DefaultBatchID = pendingDescBatchID.Default.(string)
	// pendingDescParentTaskID is the schema descriptor for parent_task_id field.
	pendingDescParentTaskID := pendingMixinFields0[13].Descriptor()
	// pending.DefaultParentTaskID holds the default value on creation for the parent_task_id field.
	pending.DefaultParentTaskID = pendingDescParentTaskID.Default.(int64)
	// pendingDescCreatedAt is the schema descriptor for created_at field.
	pendingDescCreatedAt := pendingMixinFields0[14].Descriptor()
	// pending.DefaultCreatedAt holds the default value on creation for the created_at field.
	pending.DefaultCreatedAt = pendingDescCreatedAt.Default.(func() time.Time)
	// pendingDescUpdatedAt is the schema descriptor for updated_at field.
	pendingDescUpdatedAt := pendingMixinFields0[15].Descriptor()
	// pending.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pending.DefaultUpdatedAt = pendingDescUpdatedAt.Default.(func() time.Time)
	// pending.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pending.UpdateDefaultUpdatedAt = pendingDescUpdatedAt.UpdateDefault.(func() time.Time)
	processingMixin := schema.Processing{}.Mixin()
	processingMixinFields0 := processingMixin[0].Fields()
	_ = processingMixinFields0
	processingFields := schema.Processing{}.Fields()
	_ = processingFields
	// processingDescType is the schema descriptor for type field.
	processingDescType := processingMixinFields0[1].Descriptor()
	// processing.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	processing.TypeValidator = processingDescType.Validators[0].(func(string) error)
	// processingDescPriority is the schema descriptor for priority field.
	processingDescPriority := processingMixinFields0[2].Descriptor()
	// processing.DefaultPriority holds the default value on creation for the priority field.
	processing.DefaultPriority = processingDescPriority.Default.(string)
	// processingDescExecMode is the schema descriptor for exec_mode field.
	processingDescExecMode := processingMixinFields0[3].Descriptor()
	// processing.DefaultExecMode holds the default value on creation for the exec_mode field.
	processing.DefaultExecMode = processingDescExecMode.Default.(string)
	// processingDescTimeoutMs is the schema descriptor for timeout_ms field.
	processingDescTimeoutMs := processingMixinFields0[5].Descriptor()
	// processing.DefaultTimeoutMs holds the default value on creation for the timeout_ms field.
	processing.DefaultTimeoutMs = processingDescTimeoutMs.Default.(int64)
	// processingDescMaxAttempts is the schema descriptor for max_attempts field.
	processingDescMaxAttempts := processingMixinFields0[6].Descriptor()
	// processing.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	processing.DefaultMaxAttempts = processingDescMaxAttempts.Default.(int32)
	// processingDescAttempts is the schema descriptor for attempts field.
	processingDescAttempts := processingMixinFields0[7].Descriptor()
	// processing.DefaultAttempts holds the default value on creation for the attempts field.
	processing.DefaultAttempts = processingDescAttempts.Default.(int64)
	// processingDescOwnerNode is the schema descriptor for owner_node field.
	processingDescOwnerNode := processingMixinFields0[8].Descriptor()
	// processing.DefaultOwnerNode holds the default value on creation for the owner_node field.
	processing.DefaultOwnerNode = processingDescOwnerNode.Default.(string)
	// processingDescError is the schema descriptor for error field.
	processingDescError := processingMixinFields0[9].Descriptor()
	// processing.DefaultError holds the default value on creation for the error field.
	processing.DefaultError = processingDescError.Default.(string)
	// processingDescIdempotencyKey is the schema descriptor for idempotency_key field.
	processingDescIdempotencyKey := processingMixinFields0[10].Descriptor()
	// processing.DefaultIdempotencyKey holds the default value on creation for the idempotency_key field.
	processing.DefaultIdempotencyKey = processingDescIdempotencyKey.Default.(string)
	// processingDescBatchID is the schema descriptor for batch_id field.
	processingDescBatchID := processingMixinFields0[11].Descriptor()
	// processing.DefaultBatchID holds the default value on creation for the batch_id field.
	processing.DefaultBatchID = processingDescBatchID.Default.(string)
	// processingDescParentTaskID is the schema descriptor for parent_task_id field.
	processingDescParentTaskID := processingMixinFields0[13].Descriptor()
	// processing.DefaultParentTaskID holds the default value on creation for the parent_task_id field.
	processing.DefaultParentTaskID = processingDescParentTaskID.Default.(int64)
	// processingDescCreatedAt is the schema descriptor for created_at field.
	processingDescCreatedAt := processingMixinFields0[14].Descriptor()
	// processing.DefaultCreatedAt holds the default value on creation for the created_at field.
	processing.DefaultCreatedAt = processingDescCreatedAt.Default.(func() time.Time)
	// processingDescUpdatedAt is the schema descriptor for updated_at field.
	processingDescUpdatedAt := processingMixinFields0[15].Descriptor()
	// processing.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	processing.DefaultUpdatedAt = processingDescUpdatedAt.Default.(func() time.Time)
	// processing.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	processing.UpdateDefaultUpdatedAt = processingDescUpdatedAt.UpdateDefault.(func() time.Time)
	resultFields := schema.Result{}.Fields()
	_ = resultFields
	// resultDescError is the schema descriptor for error field.
	resultDescError := resultFields[4].Descriptor()
	// result.DefaultError holds the default value on creation for the error field.
	result.DefaultError = resultDescError.Default.(string)
	schedulableMixin := schema.Schedulable{}.Mixin()
	schedulableMixinFields0 := schedulableMixin[0].Fields()
	_ = schedulableMixinFields0
	schedulableFields := schema.Schedulable{}.Fields()
	_ = schedulableFields
	// schedulableDescType is the schema descriptor for type field.
	schedulableDescType := schedulableMixinFields0[1].Descriptor()
	// schedulable.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	schedulable.TypeValidator = schedulableDescType.Validators[0].(func(string) error)
	// schedulableDescPriority is the schema descriptor for priority field.
	schedulableDescPriority := schedulableMixinFields0[2].Descriptor()
	// schedulable.DefaultPriority holds the default value on creation for the priority field.
	schedulable.DefaultPriority = schedulableDescPriority.Default.(string)
	// schedulableDescExecMode is the schema descriptor for exec_mode field.
	schedulableDescExecMode := schedulableMixinFields0[3].Descriptor()
	// schedulable.DefaultExecMode holds the default value on creation for the exec_mode field.
	schedulable.DefaultExecMode = schedulableDescExecMode.Default.(string)
	// schedulableDescTimeoutMs is the schema descriptor for timeout_ms field.
	schedulableDescTimeoutMs := schedulableMixinFields0[5].Descriptor()
	// schedulable.DefaultTimeoutMs holds the default value on creation for the timeout_ms field.
	schedulable.DefaultTimeoutMs = schedulableDescTimeoutMs.Default.(int64)
	// schedulableDescMaxAttempts is the schema descriptor for max_attempts field.
	schedulableDescMaxAttempts := schedulableMixinFields0[6].Descriptor()
	// schedulable.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	schedulable.DefaultMaxAttempts = schedulableDescMaxAttempts.Default.(int32)
	// schedulableDescAttempts is the schema descriptor for attempts field.
	schedulableDescAttempts := schedulableMixinFields0[7].Descriptor()
	// schedulable.DefaultAttempts holds the default value on creation for the attempts field.
	schedulable.DefaultAttempts = schedulableDescAttempts.Default.(int64)
	// schedulableDescOwnerNode is the schema descriptor for owner_node field.
	schedulableDescOwnerNode := schedulableMixinFields0[8].Descriptor()
	// schedulable.DefaultOwnerNode holds the default value on creation for the owner_node field.
	schedulable.DefaultOwnerNode = schedulableDescOwnerNode.Default.(string)
	// schedulableDescError is the schema descriptor for error field.
	schedulableDescError := schedulableMixinFields0[9].Descriptor()
	// schedulable.DefaultError holds the default value on creation for the error field.
	schedulable.DefaultError = schedulableDescError.Default.(string)
	// schedulableDescIdempotencyKey is the schema descriptor for idempotency_key field.
	schedulableDescIdempotencyKey := schedulableMixinFields0[10].Descriptor()
	// schedulable.DefaultIdempotencyKey holds the default value on creation for the idempotency_key field.
	schedulable.DefaultIdempotencyKey = schedulableDescIdempotencyKey.Default.(string)
	// schedulableDescBatchID is the schema descriptor for batch_id field.
	schedulableDescBatchID := schedulableMixinFields0[11].Descriptor()
	// schedulable.DefaultBatchID holds the default value on creation for the batch_id field.
	schedulable.DefaultBatchID = schedulableDescBatchID.Default.(string)
	// schedulableDescParentTaskID is the schema descriptor for parent_task_id field.
	schedulableDescParentTaskID := schedulableMixinFields0[13].Descriptor()
	// schedulable.DefaultParentTaskID holds the default value on creation for the parent_task_id field.
	schedulable.DefaultParentTaskID = schedulableDescParentTaskID.Default.(int64)
	// schedulableDescCreatedAt is the schema descriptor for created_at field.
	schedulableDescCreatedAt := schedulableMixinFields0[14].Descriptor()
	// schedulable.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedulable.DefaultCreatedAt = schedulableDescCreatedAt.Default.(func() time.Time)
	// schedulableDescUpdatedAt is the schema descriptor for updated_at field.
	schedulableDescUpdatedAt := schedulableMixinFields0[15].Descriptor()
	// schedulable.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schedulable.DefaultUpdatedAt = schedulableDescUpdatedAt.Default.(func() time.Time)
	// schedulable.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schedulable.UpdateDefaultUpdatedAt = schedulableDescUpdatedAt.UpdateDefault.(func() time.Time)
}
