// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/improvtrace/stateflux/store/ent/schedulable"
)

// SchedulableCreate is the builder for creating a Schedulable entity.
type SchedulableCreate struct {
	config
	mutation *SchedulableMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *SchedulableCreate) SetType(v string) *SchedulableCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SchedulableCreate) SetPriority(v string) *SchedulableCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillablePriority(v *string) *SchedulableCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetExecMode sets the "exec_mode" field.
func (_c *SchedulableCreate) SetExecMode(v string) *SchedulableCreate {
	_c.mutation.SetExecMode(v)
	return _c
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableExecMode(v *string) *SchedulableCreate {
	if v != nil {
		_c.SetExecMode(*v)
	}
	return _c
}

// SetRunAt sets the "run_at" field.
func (_c *SchedulableCreate) SetRunAt(v time.Time) *SchedulableCreate {
	_c.mutation.SetRunAt(v)
	return _c
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_c *SchedulableCreate) SetTimeoutMs(v int64) *SchedulableCreate {
	_c.mutation.SetTimeoutMs(v)
	return _c
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableTimeoutMs(v *int64) *SchedulableCreate {
	if v != nil {
		_c.SetTimeoutMs(*v)
	}
	return _c
}

// SetMaxAttempts sets the "max_attempts" field.
func (_c *SchedulableCreate) SetMaxAttempts(v int32) *SchedulableCreate {
	_c.mutation.SetMaxAttempts(v)
	return _c
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableMaxAttempts(v *int32) *SchedulableCreate {
	if v != nil {
		_c.SetMaxAttempts(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *SchedulableCreate) SetAttempts(v int64) *SchedulableCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableAttempts(v *int64) *SchedulableCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetOwnerNode sets the "owner_node" field.
func (_c *SchedulableCreate) SetOwnerNode(v string) *SchedulableCreate {
	_c.mutation.SetOwnerNode(v)
	return _c
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableOwnerNode(v *string) *SchedulableCreate {
	if v != nil {
		_c.SetOwnerNode(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *SchedulableCreate) SetError(v string) *SchedulableCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableError(v *string) *SchedulableCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *SchedulableCreate) SetIdempotencyKey(v string) *SchedulableCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableIdempotencyKey(v *string) *SchedulableCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetBatchID sets the "batch_id" field.
func (_c *SchedulableCreate) SetBatchID(v string) *SchedulableCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableBatchID(v *string) *SchedulableCreate {
	if v != nil {
		_c.SetBatchID(*v)
	}
	return _c
}

// SetCallback sets the "callback" field.
func (_c *SchedulableCreate) SetCallback(v jsontext.Value) *SchedulableCreate {
	_c.mutation.SetCallback(v)
	return _c
}

// SetParentTaskID sets the "parent_task_id" field.
func (_c *SchedulableCreate) SetParentTaskID(v int64) *SchedulableCreate {
	_c.mutation.SetParentTaskID(v)
	return _c
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableParentTaskID(v *int64) *SchedulableCreate {
	if v != nil {
		_c.SetParentTaskID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SchedulableCreate) SetCreatedAt(v time.Time) *SchedulableCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableCreatedAt(v *time.Time) *SchedulableCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SchedulableCreate) SetUpdatedAt(v time.Time) *SchedulableCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SchedulableCreate) SetNillableUpdatedAt(v *time.Time) *SchedulableCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SchedulableCreate) SetID(v int64) *SchedulableCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SchedulableMutation object of the builder.
func (_c *SchedulableCreate) Mutation() *SchedulableMutation {
	return _c.mutation
}

// Save creates the Schedulable in the database.
func (_c *SchedulableCreate) Save(ctx context.Context) (*Schedulable, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SchedulableCreate) SaveX(ctx context.Context) *Schedulable {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchedulableCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchedulableCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SchedulableCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := schedulable.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.ExecMode(); !ok {
		v := schedulable.DefaultExecMode
		_c.mutation.SetExecMode(v)
	}
	if _, ok := _c.mutation.TimeoutMs(); !ok {
		v := schedulable.DefaultTimeoutMs
		_c.mutation.SetTimeoutMs(v)
	}
	if _, ok := _c.mutation.MaxAttempts(); !ok {
		v := schedulable.DefaultMaxAttempts
		_c.mutation.SetMaxAttempts(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := schedulable.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.OwnerNode(); !ok {
		v := schedulable.DefaultOwnerNode
		_c.mutation.SetOwnerNode(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := schedulable.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		v := schedulable.DefaultIdempotencyKey
		_c.mutation.SetIdempotencyKey(v)
	}
	if _, ok := _c.mutation.BatchID(); !ok {
		v := schedulable.DefaultBatchID
		_c.mutation.SetBatchID(v)
	}
	if _, ok := _c.mutation.ParentTaskID(); !ok {
		v := schedulable.DefaultParentTaskID
		_c.mutation.SetParentTaskID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := schedulable.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := schedulable.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SchedulableCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Schedulable.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := schedulable.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Schedulable.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Schedulable.priority"`)}
	}
	if _, ok := _c.mutation.ExecMode(); !ok {
		return &ValidationError{Name: "exec_mode", err: errors.New(`ent: missing required field "Schedulable.exec_mode"`)}
	}
	if _, ok := _c.mutation.RunAt(); !ok {
		return &ValidationError{Name: "run_at", err: errors.New(`ent: missing required field "Schedulable.run_at"`)}
	}
	if _, ok := _c.mutation.TimeoutMs(); !ok {
		return &ValidationError{Name: "timeout_ms", err: errors.New(`ent: missing required field "Schedulable.timeout_ms"`)}
	}
	if _, ok := _c.mutation.MaxAttempts(); !ok {
		return &ValidationError{Name: "max_attempts", err: errors.New(`ent: missing required field "Schedulable.max_attempts"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "Schedulable.attempts"`)}
	}
	if _, ok := _c.mutation.OwnerNode(); !ok {
		return &ValidationError{Name: "owner_node", err: errors.New(`ent: missing required field "Schedulable.owner_node"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "Schedulable.error"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "Schedulable.idempotency_key"`)}
	}
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "Schedulable.batch_id"`)}
	}
	if _, ok := _c.mutation.ParentTaskID(); !ok {
		return &ValidationError{Name: "parent_task_id", err: errors.New(`ent: missing required field "Schedulable.parent_task_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Schedulable.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Schedulable.updated_at"`)}
	}
	return nil
}

func (_c *SchedulableCreate) sqlSave(ctx context.Context) (*Schedulable, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SchedulableCreate) createSpec() (*Schedulable, *sqlgraph.CreateSpec) {
	var (
		_node = &Schedulable{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schedulable.Table, sqlgraph.NewFieldSpec(schedulable.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(schedulable.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(schedulable.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.ExecMode(); ok {
		_spec.SetField(schedulable.FieldExecMode, field.TypeString, value)
		_node.ExecMode = value
	}
	if value, ok := _c.mutation.RunAt(); ok {
		_spec.SetField(schedulable.FieldRunAt, field.TypeTime, value)
		_node.RunAt = value
	}
	if value, ok := _c.mutation.TimeoutMs(); ok {
		_spec.SetField(schedulable.FieldTimeoutMs, field.TypeInt64, value)
		_node.TimeoutMs = value
	}
	if value, ok := _c.mutation.MaxAttempts(); ok {
		_spec.SetField(schedulable.FieldMaxAttempts, field.TypeInt32, value)
		_node.MaxAttempts = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(schedulable.FieldAttempts, field.TypeInt64, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.OwnerNode(); ok {
		_spec.SetField(schedulable.FieldOwnerNode, field.TypeString, value)
		_node.OwnerNode = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(schedulable.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(schedulable.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(schedulable.FieldBatchID, field.TypeString, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.Callback(); ok {
		_spec.SetField(schedulable.FieldCallback, field.TypeJSON, value)
		_node.Callback = value
	}
	if value, ok := _c.mutation.ParentTaskID(); ok {
		_spec.SetField(schedulable.FieldParentTaskID, field.TypeInt64, value)
		_node.ParentTaskID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(schedulable.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulable.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SchedulableCreateBulk is the builder for creating many Schedulable entities in bulk.
type SchedulableCreateBulk struct {
	config
	err      error
	builders []*SchedulableCreate
}

// Save creates the Schedulable entities in the database.
func (_c *SchedulableCreateBulk) Save(ctx context.Context) ([]*Schedulable, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Schedulable, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SchedulableMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SchedulableCreateBulk) SaveX(ctx context.Context) []*Schedulable {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchedulableCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchedulableCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
