// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/improvtrace/stateflux/store/ent/predicate"
	"github.com/improvtrace/stateflux/store/ent/schedulable"
)

// SchedulableUpdate is the builder for updating Schedulable entities.
type SchedulableUpdate struct {
	config
	hooks    []Hook
	mutation *SchedulableMutation
}

// Where appends a list predicates to the SchedulableUpdate builder.
func (_u *SchedulableUpdate) Where(ps ...predicate.Schedulable) *SchedulableUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *SchedulableUpdate) SetType(v string) *SchedulableUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableType(v *string) *SchedulableUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SchedulableUpdate) SetPriority(v string) *SchedulableUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillablePriority(v *string) *SchedulableUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *SchedulableUpdate) SetExecMode(v string) *SchedulableUpdate {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableExecMode(v *string) *SchedulableUpdate {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *SchedulableUpdate) SetRunAt(v time.Time) *SchedulableUpdate {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableRunAt(v *time.Time) *SchedulableUpdate {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *SchedulableUpdate) SetTimeoutMs(v int64) *SchedulableUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableTimeoutMs(v *int64) *SchedulableUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *SchedulableUpdate) AddTimeoutMs(v int64) *SchedulableUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *SchedulableUpdate) SetMaxAttempts(v int32) *SchedulableUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableMaxAttempts(v *int32) *SchedulableUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *SchedulableUpdate) AddMaxAttempts(v int32) *SchedulableUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *SchedulableUpdate) SetAttempts(v int64) *SchedulableUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableAttempts(v *int64) *SchedulableUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *SchedulableUpdate) AddAttempts(v int64) *SchedulableUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *SchedulableUpdate) SetOwnerNode(v string) *SchedulableUpdate {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableOwnerNode(v *string) *SchedulableUpdate {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *SchedulableUpdate) SetError(v string) *SchedulableUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableError(v *string) *SchedulableUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *SchedulableUpdate) SetIdempotencyKey(v string) *SchedulableUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableIdempotencyKey(v *string) *SchedulableUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *SchedulableUpdate) SetBatchID(v string) *SchedulableUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableBatchID(v *string) *SchedulableUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *SchedulableUpdate) SetCallback(v jsontext.Value) *SchedulableUpdate {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *SchedulableUpdate) AppendCallback(v jsontext.Value) *SchedulableUpdate {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *SchedulableUpdate) ClearCallback() *SchedulableUpdate {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *SchedulableUpdate) SetParentTaskID(v int64) *SchedulableUpdate {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *SchedulableUpdate) SetNillableParentTaskID(v *int64) *SchedulableUpdate {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *SchedulableUpdate) AddParentTaskID(v int64) *SchedulableUpdate {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchedulableUpdate) SetUpdatedAt(v time.Time) *SchedulableUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SchedulableMutation object of the builder.
func (_u *SchedulableUpdate) Mutation() *SchedulableMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchedulableUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchedulableUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchedulableUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchedulableUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchedulableUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulable.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchedulableUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := schedulable.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Schedulable.type": %w`, err)}
		}
	}
	return nil
}

func (_u *SchedulableUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulable.Table, schedulable.Columns, sqlgraph.NewFieldSpec(schedulable.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(schedulable.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(schedulable.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(schedulable.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(schedulable.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(schedulable.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(schedulable.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(schedulable.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(schedulable.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(schedulable.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(schedulable.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(schedulable.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(schedulable.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(schedulable.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(schedulable.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(schedulable.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schedulable.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(schedulable.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(schedulable.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(schedulable.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulable.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulable.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchedulableUpdateOne is the builder for updating a single Schedulable entity.
type SchedulableUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchedulableMutation
}

// SetType sets the "type" field.
func (_u *SchedulableUpdateOne) SetType(v string) *SchedulableUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableType(v *string) *SchedulableUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SchedulableUpdateOne) SetPriority(v string) *SchedulableUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillablePriority(v *string) *SchedulableUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *SchedulableUpdateOne) SetExecMode(v string) *SchedulableUpdateOne {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableExecMode(v *string) *SchedulableUpdateOne {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// SetRunAt sets the "run_at" field.
func (_u *SchedulableUpdateOne) SetRunAt(v time.Time) *SchedulableUpdateOne {
	_u.mutation.SetRunAt(v)
	return _u
}

// SetNillableRunAt sets the "run_at" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableRunAt(v *time.Time) *SchedulableUpdateOne {
	if v != nil {
		_u.SetRunAt(*v)
	}
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *SchedulableUpdateOne) SetTimeoutMs(v int64) *SchedulableUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableTimeoutMs(v *int64) *SchedulableUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *SchedulableUpdateOne) AddTimeoutMs(v int64) *SchedulableUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *SchedulableUpdateOne) SetMaxAttempts(v int32) *SchedulableUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableMaxAttempts(v *int32) *SchedulableUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *SchedulableUpdateOne) AddMaxAttempts(v int32) *SchedulableUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *SchedulableUpdateOne) SetAttempts(v int64) *SchedulableUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableAttempts(v *int64) *SchedulableUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *SchedulableUpdateOne) AddAttempts(v int64) *SchedulableUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetOwnerNode sets the "owner_node" field.
func (_u *SchedulableUpdateOne) SetOwnerNode(v string) *SchedulableUpdateOne {
	_u.mutation.SetOwnerNode(v)
	return _u
}

// SetNillableOwnerNode sets the "owner_node" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableOwnerNode(v *string) *SchedulableUpdateOne {
	if v != nil {
		_u.SetOwnerNode(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *SchedulableUpdateOne) SetError(v string) *SchedulableUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableError(v *string) *SchedulableUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *SchedulableUpdateOne) SetIdempotencyKey(v string) *SchedulableUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableIdempotencyKey(v *string) *SchedulableUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *SchedulableUpdateOne) SetBatchID(v string) *SchedulableUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableBatchID(v *string) *SchedulableUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCallback sets the "callback" field.
func (_u *SchedulableUpdateOne) SetCallback(v jsontext.Value) *SchedulableUpdateOne {
	_u.mutation.SetCallback(v)
	return _u
}

// AppendCallback appends value to the "callback" field.
func (_u *SchedulableUpdateOne) AppendCallback(v jsontext.Value) *SchedulableUpdateOne {
	_u.mutation.AppendCallback(v)
	return _u
}

// ClearCallback clears the value of the "callback" field.
func (_u *SchedulableUpdateOne) ClearCallback() *SchedulableUpdateOne {
	_u.mutation.ClearCallback()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *SchedulableUpdateOne) SetParentTaskID(v int64) *SchedulableUpdateOne {
	_u.mutation.ResetParentTaskID()
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *SchedulableUpdateOne) SetNillableParentTaskID(v *int64) *SchedulableUpdateOne {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// AddParentTaskID adds value to the "parent_task_id" field.
func (_u *SchedulableUpdateOne) AddParentTaskID(v int64) *SchedulableUpdateOne {
	_u.mutation.AddParentTaskID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchedulableUpdateOne) SetUpdatedAt(v time.Time) *SchedulableUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SchedulableMutation object of the builder.
func (_u *SchedulableUpdateOne) Mutation() *SchedulableMutation {
	return _u.mutation
}

// Where appends a list predicates to the SchedulableUpdate builder.
func (_u *SchedulableUpdateOne) Where(ps ...predicate.Schedulable) *SchedulableUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchedulableUpdateOne) Select(field string, fields ...string) *SchedulableUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Schedulable entity.
func (_u *SchedulableUpdateOne) Save(ctx context.Context) (*Schedulable, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchedulableUpdateOne) SaveX(ctx context.Context) *Schedulable {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchedulableUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchedulableUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchedulableUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulable.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchedulableUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := schedulable.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Schedulable.type": %w`, err)}
		}
	}
	return nil
}

func (_u *SchedulableUpdateOne) sqlSave(ctx context.Context) (_node *Schedulable, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulable.Table, schedulable.Columns, sqlgraph.NewFieldSpec(schedulable.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Schedulable.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedulable.FieldID)
		for _, f := range fields {
			if !schedulable.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedulable.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(schedulable.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(schedulable.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(schedulable.FieldExecMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunAt(); ok {
		_spec.SetField(schedulable.FieldRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(schedulable.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(schedulable.FieldTimeoutMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(schedulable.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(schedulable.FieldMaxAttempts, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(schedulable.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(schedulable.FieldAttempts, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerNode(); ok {
		_spec.SetField(schedulable.FieldOwnerNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(schedulable.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(schedulable.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(schedulable.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Callback(); ok {
		_spec.SetField(schedulable.FieldCallback, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCallback(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schedulable.FieldCallback, value)
		})
	}
	if _u.mutation.CallbackCleared() {
		_spec.ClearField(schedulable.FieldCallback, field.TypeJSON)
	}
	if value, ok := _u.mutation.ParentTaskID(); ok {
		_spec.SetField(schedulable.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentTaskID(); ok {
		_spec.AddField(schedulable.FieldParentTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulable.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Schedulable{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulable.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
