// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/improvtrace/stateflux/store/ent/schedulable"
)

// Schedulable is the model entity for the Schedulable schema.
type Schedulable struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// ExecMode holds the value of the "exec_mode" field.
	ExecMode string `json:"exec_mode,omitempty"`
	// RunAt holds the value of the "run_at" field.
	RunAt time.Time `json:"run_at,omitempty"`
	// TimeoutMs holds the value of the "timeout_ms" field.
	TimeoutMs int64 `json:"timeout_ms,omitempty"`
	// MaxAttempts holds the value of the "max_attempts" field.
	MaxAttempts int32 `json:"max_attempts,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int64 `json:"attempts,omitempty"`
	// OwnerNode holds the value of the "owner_node" field.
	OwnerNode string `json:"owner_node,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// BatchID holds the value of the "batch_id" field.
	BatchID string `json:"batch_id,omitempty"`
	// Callback holds the value of the "callback" field.
	Callback jsontext.Value `json:"callback,omitempty"`
	// ParentTaskID holds the value of the "parent_task_id" field.
	ParentTaskID int64 `json:"parent_task_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Schedulable) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedulable.FieldCallback:
			values[i] = new([]byte)
		case schedulable.FieldID, schedulable.FieldTimeoutMs, schedulable.FieldMaxAttempts, schedulable.FieldAttempts, schedulable.FieldParentTaskID:
			values[i] = new(sql.NullInt64)
		case schedulable.FieldType, schedulable.FieldPriority, schedulable.FieldExecMode, schedulable.FieldOwnerNode, schedulable.FieldError, schedulable.FieldIdempotencyKey, schedulable.FieldBatchID:
			values[i] = new(sql.NullString)
		case schedulable.FieldRunAt, schedulable.FieldCreatedAt, schedulable.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Schedulable fields.
func (_m *Schedulable) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedulable.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case schedulable.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case schedulable.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case schedulable.FieldExecMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exec_mode", values[i])
			} else if value.Valid {
				_m.ExecMode = value.String
			}
		case schedulable.FieldRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field run_at", values[i])
			} else if value.Valid {
				_m.RunAt = value.Time
			}
		case schedulable.FieldTimeoutMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_ms", values[i])
			} else if value.Valid {
				_m.TimeoutMs = value.Int64
			}
		case schedulable.FieldMaxAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_attempts", values[i])
			} else if value.Valid {
				_m.MaxAttempts = int32(value.Int64)
			}
		case schedulable.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = value.Int64
			}
		case schedulable.FieldOwnerNode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_node", values[i])
			} else if value.Valid {
				_m.OwnerNode = value.String
			}
		case schedulable.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case schedulable.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case schedulable.FieldBatchID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value.Valid {
				_m.BatchID = value.String
			}
		case schedulable.FieldCallback:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field callback", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Callback); err != nil {
					return fmt.Errorf("unmarshal field callback: %w", err)
				}
			}
		case schedulable.FieldParentTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_task_id", values[i])
			} else if value.Valid {
				_m.ParentTaskID = value.Int64
			}
		case schedulable.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case schedulable.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Schedulable.
// This includes values selected through modifiers, order, etc.
func (_m *Schedulable) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Schedulable.
// Note that you need to call Schedulable.Unwrap() before calling this method if this Schedulable
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Schedulable) Update() *SchedulableUpdateOne {
	return NewSchedulableClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Schedulable entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Schedulable) Unwrap() *Schedulable {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Schedulable is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Schedulable) String() string {
	var builder strings.Builder
	builder.WriteString("Schedulable(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("exec_mode=")
	builder.WriteString(_m.ExecMode)
	builder.WriteString(", ")
	builder.WriteString("run_at=")
	builder.WriteString(_m.RunAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("timeout_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutMs))
	builder.WriteString(", ")
	builder.WriteString("max_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxAttempts))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("owner_node=")
	builder.WriteString(_m.OwnerNode)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("batch_id=")
	builder.WriteString(_m.BatchID)
	builder.WriteString(", ")
	builder.WriteString("callback=")
	builder.WriteString(fmt.Sprintf("%v", _m.Callback))
	builder.WriteString(", ")
	builder.WriteString("parent_task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentTaskID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Schedulables is a parsable slice of Schedulable.
type Schedulables []*Schedulable
