// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/improvtrace/stateflux/store/ent/predicate"
	"github.com/improvtrace/stateflux/store/ent/schedulable"
)

// SchedulableDelete is the builder for deleting a Schedulable entity.
type SchedulableDelete struct {
	config
	hooks    []Hook
	mutation *SchedulableMutation
}

// Where appends a list predicates to the SchedulableDelete builder.
func (_d *SchedulableDelete) Where(ps ...predicate.Schedulable) *SchedulableDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SchedulableDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SchedulableDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SchedulableDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(schedulable.Table, sqlgraph.NewFieldSpec(schedulable.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SchedulableDeleteOne is the builder for deleting a single Schedulable entity.
type SchedulableDeleteOne struct {
	_d *SchedulableDelete
}

// Where appends a list predicates to the SchedulableDelete builder.
func (_d *SchedulableDeleteOne) Where(ps ...predicate.Schedulable) *SchedulableDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SchedulableDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{schedulable.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SchedulableDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
