// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Completed is the predicate function for completed builders.
type Completed func(*sql.Selector)

// Payload is the predicate function for payload builders.
type Payload func(*sql.Selector)

// Pending is the predicate function for pending builders.
type Pending func(*sql.Selector)

// Processing is the predicate function for processing builders.
type Processing func(*sql.Selector)

// Result is the predicate function for result builders.
type Result func(*sql.Selector)

// Schedulable is the predicate function for schedulable builders.
type Schedulable func(*sql.Selector)
