// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package stateflux

import (
	"context"
	"github.com/google/wire"
	"github.com/improvtrace/stateflux/internal/config"
	"github.com/improvtrace/stateflux/internal/server"
)

// Injectors from wire.go:

// newApplication 是 wire 的装配器（§15.1#1）：按配置装配出应用实例与释放函数，
// 仅由 NewServeDeps 包装成 ServeDeps 注入 serve 子命令。
func newApplication(ctx context.Context, cfg config.Config) (*server.App, func(), error) {
	view, err := provideClusterView(cfg)
	if err != nil {
		return nil, nil, err
	}
	cache, cleanup := provideClusterCache(ctx, cfg, view)
	string2 := provideNodeID(cache)
	data, cleanup2, err := dataOpen(ctx, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dialer := provideDialer()
	eventBus, err := provideEventBus(cfg, data, dialer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registry, err := provideTaskRegistry()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	codec := provideCodec(registry)
	handlerRegistry, err := provideHandlerRegistry()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cacheviewView, err := provideCacheView(cfg, data)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	resultPublisher := provideResultPublisher(cfg, eventBus, cache, cacheviewView)
	metrics, err := provideMetrics()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtime := provideWorkerRuntime(cfg, string2, eventBus, codec, handlerRegistry, resultPublisher, cacheviewView, metrics)
	snowflake := provideSnowflake(string2)
	store := provideStore(data, snowflake)
	collector := provideCollector(store, metrics)
	executorServer := provideExecutorServer(runtime, collector, metrics)
	workerRegistry, err := provideCapabilityRegistry()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	capabilityServer := provideCapabilityServer(workerRegistry, metrics)
	dispatcher := provideDispatcher(cfg, string2, eventBus, cache, cacheviewView, codec, metrics)
	forwarder := provideForwarder(cfg, string2, dialer, cache)
	dispatchServer := provideDispatchServer(cfg, string2, dispatcher, cache, forwarder, metrics)
	coherenceStore := provideCoherenceStore()
	coherenceServer := provideCoherenceServer(coherenceStore, cacheviewView, metrics)
	forwardRegistry := provideForwardRegistry()
	forwardServer := provideForwardServer(cfg, string2, forwardRegistry, forwarder)
	grpcServer := provideGRPCServer(executorServer, capabilityServer, dispatchServer, coherenceServer, forwardServer)
	health := server.NewHealth()
	httpServer := server.NewHTTPServer(cfg, health)
	statefluxWorkerComponent := provideWorkerComponent(runtime)
	ledgerCycle := provideCycle(cfg, string2, store, dispatcher, eventBus, metrics)
	taskNotifier, cleanup3 := provideTaskNotifier(cfg)
	group := provideSchedulerGroup(cfg, ledgerCycle, coherenceStore, taskNotifier, metrics)
	statefluxSchedulerComponent := provideSchedulerComponent(group)
	channelProbe := provideChannelProbe(data)
	reconciler := provideReconciler(cfg, store, cacheviewView, channelProbe, metrics)
	statefluxReconcileComponent := provideReconcileComponent(reconciler)
	coherenceSyncer := provideCoherenceSyncer(cfg, string2, coherenceStore, cache, dialer, metrics)
	statefluxSyncerComponent := provideSyncerComponent(coherenceSyncer)
	coherencePuller := provideCoherencePuller(cfg, string2, coherenceStore, cache, dialer, cacheviewView, metrics)
	statefluxPullerComponent := providePullerComponent(coherencePuller)
	factoryRegistry, err := provideFactoryRegistry(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	enqueuer := provideEnqueuer(store, snowflake, cfg)
	manager := provideFactoryManager(factoryRegistry, enqueuer)
	statefluxFactoryComponent := provideFactoryComponent(manager)
	runner := provideCollectorRunner(cfg, eventBus, collector, metrics)
	statefluxCollectorRunnerComponent := provideCollectorRunnerComponent(runner)
	v := provideComponents(cfg, string2, cache, eventBus, statefluxWorkerComponent, statefluxSchedulerComponent, statefluxReconcileComponent, statefluxSyncerComponent, statefluxPullerComponent, statefluxFactoryComponent, statefluxCollectorRunnerComponent)
	app, err := provideApp(cfg, grpcServer, httpServer, v, forwardRegistry, dispatchServer, health)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// ProviderSet 是全部装配提供者（§15.1#1）。
var ProviderSet = wire.NewSet(

	provideMetrics,
	provideDialer,
	provideClusterView,
	provideClusterCache,
	provideNodeID,
	provideEventBus,
	provideCacheView,
	dataOpen,

	provideStore,
	provideSnowflake,
	provideTaskRegistry,
	provideCodec,
	provideEnqueuer,
	provideFactoryRegistry,
	provideFactoryManager,
	provideFactoryComponent,

	provideCapabilityRegistry,
	provideHandlerRegistry,
	provideResultPublisher,
	provideWorkerRuntime,
	provideWorkerComponent,

	provideForwarder,
	provideForwardRegistry,
	provideForwardServer,
	provideDispatcher,
	provideDispatchServer,

	provideCoherenceStore,
	provideCoherenceServer,
	provideCoherenceSyncer,
	provideCoherencePuller,
	provideSyncerComponent,
	providePullerComponent,

	provideCollector,
	provideCollectorRunner,
	provideCollectorRunnerComponent,
	provideReconciler,
	provideReconcileComponent,
	provideChannelProbe,

	provideCycle,
	provideSchedulerGroup,
	provideSchedulerComponent,
	provideTaskNotifier,

	provideExecutorServer,
	provideCapabilityServer,
	provideGRPCServer,
	provideComponents, server.NewHealth, server.NewHTTPServer, provideApp,
)
