// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CompletedTasksColumns holds the columns for the "completed_tasks" table.
	CompletedTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "priority", Type: field.TypeString, Default: "normal"},
		{Name: "exec_mode", Type: field.TypeString, Default: "async"},
		{Name: "run_at", Type: field.TypeTime},
		{Name: "timeout_ms", Type: field.TypeInt64, Default: 60000},
		{Name: "max_attempts", Type: field.TypeInt32, Default: 3},
		{Name: "attempts", Type: field.TypeInt64, Default: 0},
		{Name: "owner_node", Type: field.TypeString, Default: ""},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "idempotency_key", Type: field.TypeString, Default: ""},
		{Name: "batch_id", Type: field.TypeString, Default: ""},
		{Name: "callback", Type: field.TypeJSON, Nullable: true},
		{Name: "parent_task_id", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "outcome", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime},
	}
	// CompletedTasksTable holds the schema information for the "completed_tasks" table.
	CompletedTasksTable = &schema.Table{
		Name:       "completed_tasks",
		Columns:    CompletedTasksColumns,
		PrimaryKey: []*schema.Column{CompletedTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "completed_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{CompletedTasksColumns[1], CompletedTasksColumns[14]},
			},
			{
				Name:    "completed_outcome",
				Unique:  false,
				Columns: []*schema.Column{CompletedTasksColumns[16]},
			},
			{
				Name:    "completed_batch_id",
				Unique:  false,
				Columns: []*schema.Column{CompletedTasksColumns[11]},
			},
		},
	}
	// TaskPayloadsColumns holds the columns for the "task_payloads" table.
	TaskPayloadsColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeInt64, Increment: true},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TaskPayloadsTable holds the schema information for the "task_payloads" table.
	TaskPayloadsTable = &schema.Table{
		Name:       "task_payloads",
		Columns:    TaskPayloadsColumns,
		PrimaryKey: []*schema.Column{TaskPayloadsColumns[0]},
	}
	// PendingTasksColumns holds the columns for the "pending_tasks" table.
	PendingTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "priority", Type: field.TypeString, Default: "normal"},
		{Name: "exec_mode", Type: field.TypeString, Default: "async"},
		{Name: "run_at", Type: field.TypeTime},
		{Name: "timeout_ms", Type: field.TypeInt64, Default: 60000},
		{Name: "max_attempts", Type: field.TypeInt32, Default: 3},
		{Name: "attempts", Type: field.TypeInt64, Default: 0},
		{Name: "owner_node", Type: field.TypeString, Default: ""},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "idempotency_key", Type: field.TypeString, Default: ""},
		{Name: "batch_id", Type: field.TypeString, Default: ""},
		{Name: "callback", Type: field.TypeJSON, Nullable: true},
		{Name: "parent_task_id", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PendingTasksTable holds the schema information for the "pending_tasks" table.
	PendingTasksTable = &schema.Table{
		Name:       "pending_tasks",
		Columns:    PendingTasksColumns,
		PrimaryKey: []*schema.Column{PendingTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "pending_priority_run_at",
				Unique:  false,
				Columns: []*schema.Column{PendingTasksColumns[2], PendingTasksColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						PendingTasksColumns[2].Name: true,
					},
				},
			},
			{
				Name:    "pending_idempotency_key",
				Unique:  false,
				Columns: []*schema.Column{PendingTasksColumns[10]},
			},
		},
	}
	// ProcessingTasksColumns holds the columns for the "processing_tasks" table.
	ProcessingTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "priority", Type: field.TypeString, Default: "normal"},
		{Name: "exec_mode", Type: field.TypeString, Default: "async"},
		{Name: "run_at", Type: field.TypeTime},
		{Name: "timeout_ms", Type: field.TypeInt64, Default: 60000},
		{Name: "max_attempts", Type: field.TypeInt32, Default: 3},
		{Name: "attempts", Type: field.TypeInt64, Default: 0},
		{Name: "owner_node", Type: field.TypeString, Default: ""},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "idempotency_key", Type: field.TypeString, Default: ""},
		{Name: "batch_id", Type: field.TypeString, Default: ""},
		{Name: "callback", Type: field.TypeJSON, Nullable: true},
		{Name: "parent_task_id", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProcessingTasksTable holds the schema information for the "processing_tasks" table.
	ProcessingTasksTable = &schema.Table{
		Name:       "processing_tasks",
		Columns:    ProcessingTasksColumns,
		PrimaryKey: []*schema.Column{ProcessingTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "processing_updated_at",
				Unique:  false,
				Columns: []*schema.Column{ProcessingTasksColumns[15]},
			},
			{
				Name:    "processing_type",
				Unique:  false,
				Columns: []*schema.Column{ProcessingTasksColumns[1]},
			},
			{
				Name:    "processing_idempotency_key",
				Unique:  false,
				Columns: []*schema.Column{ProcessingTasksColumns[10]},
			},
		},
	}
	// TaskResultsColumns holds the columns for the "task_results" table.
	TaskResultsColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeInt64, Increment: true},
		{Name: "outcome", Type: field.TypeString},
		{Name: "attempt", Type: field.TypeInt64},
		{Name: "result", Type: field.TypeJSON, Nullable: true},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "completed_at", Type: field.TypeTime},
	}
	// TaskResultsTable holds the schema information for the "task_results" table.
	TaskResultsTable = &schema.Table{
		Name:       "task_results",
		Columns:    TaskResultsColumns,
		PrimaryKey: []*schema.Column{TaskResultsColumns[0]},
	}
	// SchedulableTasksColumns holds the columns for the "schedulable_tasks" table.
	SchedulableTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "priority", Type: field.TypeString, Default: "normal"},
		{Name: "exec_mode", Type: field.TypeString, Default: "async"},
		{Name: "run_at", Type: field.TypeTime},
		{Name: "timeout_ms", Type: field.TypeInt64, Default: 60000},
		{Name: "max_attempts", Type: field.TypeInt32, Default: 3},
		{Name: "attempts", Type: field.TypeInt64, Default: 0},
		{Name: "owner_node", Type: field.TypeString, Default: ""},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "idempotency_key", Type: field.TypeString, Default: ""},
		{Name: "batch_id", Type: field.TypeString, Default: ""},
		{Name: "callback", Type: field.TypeJSON, Nullable: true},
		{Name: "parent_task_id", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SchedulableTasksTable holds the schema information for the "schedulable_tasks" table.
	SchedulableTasksTable = &schema.Table{
		Name:       "schedulable_tasks",
		Columns:    SchedulableTasksColumns,
		PrimaryKey: []*schema.Column{SchedulableTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schedulable_priority_run_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulableTasksColumns[2], SchedulableTasksColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						SchedulableTasksColumns[2].Name: true,
					},
				},
			},
			{
				Name:    "schedulable_idempotency_key",
				Unique:  false,
				Columns: []*schema.Column{SchedulableTasksColumns[10]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CompletedTasksTable,
		TaskPayloadsTable,
		PendingTasksTable,
		ProcessingTasksTable,
		TaskResultsTable,
		SchedulableTasksTable,
	}
)

func init() {
	CompletedTasksTable.Annotation = &entsql.Annotation{
		Table: "completed_tasks",
	}
	TaskPayloadsTable.Annotation = &entsql.Annotation{
		Table: "task_payloads",
	}
	PendingTasksTable.Annotation = &entsql.Annotation{
		Table: "pending_tasks",
	}
	ProcessingTasksTable.Annotation = &entsql.Annotation{
		Table: "processing_tasks",
	}
	TaskResultsTable.Annotation = &entsql.Annotation{
		Table: "task_results",
	}
	SchedulableTasksTable.Annotation = &entsql.Annotation{
		Table: "schedulable_tasks",
	}
}
